const LABELS = {
	"section.ready": "现在可以开始的",
	"section.scope": "当前范围",
	"section.what": "要做的事",
	"section.done": "每件做完算什么样",
	"section.founder": "要回来找 founder 的",
	"section.gaps": "缺什么、缺在哪",
	"cell.provenance": "出处",
	"cell.observed_at": "看到它的时间",
	"cell.ledger_note": "账面状态,不代表进程一定活着",
	"cell.value": "内容",
	"cell.source_updated_at": "来源更新时间",
	"cell.missing": "缺失",
	"cell.linear": "Linear",
	"cell.derived_from": "由 {from} 推出",
	"page.title": "项目执行页面",
	"page.generated_at": "生成时间",
	"page.project": "项目",
	"page.overview": "执行范围总览",
	"page.ready_rule_note": "已获 founder 裁定的规则 ready.v1",
	"page.scope_rule_note": "已获 founder 裁定的规则 scope.v1",
	"page.decided_rule_note": "已获 founder 裁定的规则 {rule}",
	"page.default_rule_note": "未获 founder 裁定的默认规则 {rule}",
	"page.none": "无",
	"page.item_detail": "子单 {id}",
	"page.what": "是什么",
	"page.why": "为什么",
	"page.done_outcome": "做完你看到",
	"page.waiting_for": "等谁",
	"page.waiting_on_me": "谁在等我",
	"page.missing_acceptance": "缺验收",
	"page.no_dependency": "没有前置依赖",
	"page.no_dependents": "没有范围内的 issue 在等它",
	"page.external_dependency": "(范围外)",
	"page.blocker_state": "状态:{state}",
	"page.unlocks": "做完会让 {items} 继续",
	"page.accounted_execution": "账面执行体",
	"page.founder_yes": "要回来找 founder",
	"page.founder_no": "未标记回来找 founder",
	"page.source_link": "出处链接",
	"page.all_cells": "{count} 格出处与时间",
	"page.items_unit": "张子单",
	"page.roots_unit": "个 active 父单",
	"page.gaps_unit": "项缺口",
	"page.acceptance_full": "验收原文",
	"page.blockers_all": "全部前置依赖",
	"page.dependents_all": "全部下游",
	"page.execution_facts": "执行事实",
	"cell.header.scope_definition": "范围规则",
	"cell.header.roots": "active 父单",
	"cell.header.items": "范围内子单",
	"cell.done_definition": "做完定义",
	"cell.founder_items": "回来找 founder 的子单",
	"cell.ready_items": "现在可以开始的子单",
	"cell.gaps": "缺口集合",
	"cell.item.title": "标题",
	"cell.item.url": "链接",
	"cell.item.state": "状态",
	"cell.item.priority": "优先级",
	"cell.item.blocked_by": "全部前置依赖",
	"cell.item.blocks": "全部下游",
	"cell.item.acceptance": "验收原文",
	"cell.item.founder_named": "需要回来找 founder",
	"cell.item.session": "会话账面事实",
	"cell.item.run": "工作流账面事实",
	"cell.item.attempt": "节点尝试账面事实",
	"cell.item.gates": "审批门事实",
	"cell.item.carriers": "交付载体事实",
	"cell.item.land": "落地事实",
	"value.yes": "是",
	"value.no": "否",
	"value.present": "有",
	"value.absent": "缺",
	"time.minutes_ago": "{n} 分钟前",
	"founder.none": "0 件(标签 founder-review 当前无命中)",
} as const;

export type LabelKey = keyof typeof LABELS;

export function label(
	key: LabelKey,
	params: Record<string, string | number> = {},
): string {
	const template = LABELS[key];
	if (!template) throw new Error(`Unknown epic-page label: ${key}`);
	return template.replace(/\{([a-z_]+)\}/g, (_match, name: string) => {
		if (!(name in params)) {
			throw new Error(`Missing epic-page label parameter: ${name}`);
		}
		return String(params[name]);
	});
}
