const LABELS = {
	"section.attention": "现在要你看",
	"attention.what": "这是什么",
	"attention.action": "需要你做什么",
	"attention.wait": "等了多久",
	"attention.where": "去哪儿做",
	"attention.unknown": "不知道",
	"attention.legacy": "不知道（旧版尚未采集）",
	"attention.wait_unknown": "自 不知道 起,已等 不知道 小时",
	"attention.wait_invalid": "自 不知道 起,已等 不知道 小时（起点无效）",
	"attention.wait_value": "自 {time} 起,已等 {n} 小时（{date} UTC）",
	"attention.wait_short": "（未满一小时）",
	"attention.recipient":
		"记录收件方：{role}；当前在等 {role} 回复，你可进入讨论串了解情况",
	"attention.open_thread": "打开该单讨论串",
	"attention.sources": "全部 {n} 条来源",
	"attention.more_questions": "另有 {n} 条待回答记录",
	"attention.empty": "现在没有等你的事",
	"attention.count": "有 {n} 件等你处理的事",
	"attention.incomplete": "已知 {n} 条记录，清单不完整",
	"attention.identity_incomplete": "身份尚未核齐，同一件事可能暂列多条",
	"attention.budget_incomplete": "体积上限，部分事项未显示",
	"attention.scope_unavailable": "Epic 范围不可用，请补齐 Epic/日常筐前置",
	"lead_note.title": "Lead 判断（角色声明）",
	"lead_note.disclosure": "角色为提交方声明，未核验具体作者",
	"lead_note.stale": "较早判断",
	"audit.acceptance_source": "到 Linear 看完整验收",
	"terminal.done": "{n} 张已完成",
	"terminal.canceled": "{n} 张已取消",
	"blocker.more": " 等 {n} 张",
	"progress.unknown": "不知道",
	"cell.item.parent": "父单",
	"cell.header.root_counts": "子单计数",
	"section.epics": "在做的 Epic",
	"section.epics_count": "{n} 个(全做完的不列;状态照抄 Linear)",
	"epic.hidden_done": "另有 {n} 个 Epic 全做完,不列",
	"epic.none": "范围内没有还没做完的 Epic",
	"epic.scope_unavailable": "Epic 范围不可用,这一版没有 Epic 卡",
	"epic.unattached": "没挂 Epic(取数时它的父单为空)",
	"counts.live": "{n} 在跑",
	"counts.waiting": "{n} 等依赖",
	"counts.free": "{n} 可起跑",
	"counts.idle": "{n} 未开始",
	"counts.total": "共 {n}",
	"counts.missing": "计数缺失:不认识状态类型 {type}",
	"epic.all_waiting": "整块在等 {blockers}",
	"epic.terminal_tail": "另有 {tail}(不列)",
	"child.live": "在跑",
	"child.waiting": "等 {blockers}",
	"child.free": "可起跑",
	"child.idle": "未开始",
	"child.unknown_type": "{state}(未知类型)",
	"blocker.outside": "(范围外)",
	"blocker.other_epic": "(在 {root})",
	"blocker.unattached": "(没挂 Epic)",
	"progress.live": "到「{node}」· 第 {attempt} 次 · 会话 {status}",
	"progress.live_no_run": "在跑(引擎还没报节点)",
	"progress.waiting": "被 {blockers} 挡着,没起跑",
	"progress.free": "原本等 {blockers},它已经做完了 —— 现在没人挡着",
	"progress.idle": "还没起跑",
	"progress.missing": "执行事实缺失:{reasons}",
	"progress.source": "机器测的",
	"section.lead_panel": "给 Lead 看的诊断(默认收起)",
	"audit.linear_issue": "Linear issue {id}",
	"audit.seen": "看到 {at}",
	"audit.source_updated": "源 {at}",
	"view.rule_note": "页面展示规则 {rule} · 由 {from} 推出 · 输入最新观测 {at}",
	"view.order_desc":
		"Epic 按 Linear 状态分组、组内按单号;子单 在跑 → 等依赖 → 可起跑 → 未开始、组内按单号",
	"audit.root_projection": "本 Epic 在「active 父单」格里的那一项",

	"section.ready": "现在可以开始的",
	"section.review": "依赖需要减法的地方",
	"section.scope": "当前范围",
	"section.what": "要做的事",
	"section.done": "每件做完算什么样",
	"section.founder": "要回来找 founder 的",
	"section.gaps": "缺什么、缺在哪",
	"section.stuck": "卡住说了一声的",
	"section.waiting_founder": "在等 founder 的",
	"cell.provenance": "出处",
	"cell.observed_at": "看到它的时间",
	"cell.ledger_note": "账面状态,不代表进程一定活着",
	"cell.value": "内容",
	"cell.source_updated_at": "来源更新时间",
	"cell.missing": "缺失",
	"cell.linear": "Linear",
	"cell.derived_from": "由 {from} 推出",
	"page.title": "项目执行页面",
	"page.generated_at": "生成时间",
	"page.project": "项目",
	"page.overview": "执行范围总览",
	"page.ready_rule_note": "已获 founder 裁定的规则 ready.v1",
	"page.scope_rule_note": "已获 founder 裁定的规则 scope.v2",
	"page.decided_rule_note": "已获 founder 裁定的规则 {rule}",
	"page.default_rule_note": "未获 founder 裁定的默认规则 {rule}",
	"page.none": "无",
	"page.signal_none": "无",
	"page.freshness": "这页多旧",
	"page.item_detail": "子单 {id}",
	"page.what": "是什么",
	"page.why": "为什么",
	"page.done_outcome": "做完你看到",
	"page.waiting_for": "等谁",
	"page.waiting_on_me": "谁在等我",
	"page.missing_acceptance": "缺验收",
	"page.no_dependency": "没有前置依赖",
	"page.no_dependents": "没有范围内的 issue 在等它",
	"page.external_dependency": "(范围外)",
	"page.blocker_state": "状态:{state}",
	"page.unlocks": "做完会让 {items} 继续",
	"page.accounted_execution": "账面执行体",
	"page.founder_yes": "要回来找 founder",
	"page.founder_no": "未标记回来找 founder",
	"page.source_link": "出处链接",
	"page.all_cells": "{count} 格出处与时间",
	"page.items_unit": "张子单",
	"page.roots_unit": "个 active 父单",
	"page.gaps_unit": "项缺口",
	"page.acceptance_full": "验收原文",
	"page.blockers_all": "全部前置依赖",
	"page.dependents_all": "全部下游",
	"page.execution_facts": "执行事实",
	"freshness.trigger.event": "事件触发",
	"freshness.trigger.scan": "到点扫描",
	"freshness.trigger.manual": "手动",
	"freshness.current": "本版",
	"freshness.last_generated": "上次成功生成",
	"freshness.last_published": "固定页上次成功发布",
	"freshness.failures":
		"本版成功之前,上次成功发布之后失败 {n} 次,最近 {token} @ {at}",
	"freshness.next_scan": "下一次到点扫描预计",
	"freshness.oldest_source": "来源最旧观测",
	"freshness.hosted": "固定页 {token8} 上次发布 {at}",
	"freshness.opened_age": "你打开时它已 {minutes} 分钟旧",
	"signal.kind.declared_blocked": "IC 声明卡住",
	"signal.kind.runner_stopped": "runner 停机({reason})",
	"signal.kind.question_pending": "有问题等 Lead 回",
	"signal.kind.run_held": "run 被 hold",
	"signal.kind.waiting_founder": "在等 founder",
	"tick.stuck_line": "- 卡住说了一声的 {n} 张:{items}",
	"cell.header.scope_definition": "范围规则",
	"cell.header.roots": "active 父单",
	"cell.header.items": "范围内子单",
	"cell.done_definition": "做完定义",
	"cell.founder_items": "回来找 founder 的子单",
	"cell.ready_items": "现在可以开始的子单",
	"cell.dependency_review": "依赖审阅",
	"cell.gaps": "缺口集合",
	"cell.stuck_items": "卡住信号集合",
	"cell.item.title": "标题",
	"cell.item.url": "链接",
	"cell.item.state": "状态",
	"cell.item.priority": "优先级",
	"cell.item.blocked_by": "全部前置依赖",
	"cell.item.blocks": "全部下游",
	"cell.item.acceptance": "验收原文",
	"cell.item.founder_named": "需要回来找 founder",
	"cell.item.session": "会话账面事实",
	"cell.item.run": "工作流账面事实",
	"cell.item.attempt": "节点尝试账面事实",
	"cell.item.gates": "审批门事实",
	"cell.item.carriers": "交付载体事实",
	"cell.item.land": "落地事实",
	"value.yes": "是",
	"value.no": "否",
	"value.present": "有",
	"value.absent": "缺",
	"time.minutes_ago": "{n} 分钟前",
	"founder.none": "0 件(标签 founder-review 当前无命中)",
	"review.canceled_blocker":
		"{item} 还在等已取消的 {blocker} —— 删这条边,或改指别的单",
	"review.cycle": "{members} 互相等,谁都不会开始 —— 至少删一条边",
	"review.all_blocked":
		"{n} 件没做完、0 件能开始 —— 下面是它们各自在等的边,逐条判断:等它做完,还是删边",
	"review.blocking_edge": "{blocked} 在等 {blocker}(状态:{state}{scope})",
	"review.blocking_edges_truncated": "…只列前 50 条",
	"review.none":
		"0 个可观测警报。这不代表没有该减的边:blocker 还活着、但已经不需要等它的那种,页面看不出来,只能由 Lead 用 remove 说出来",
} as const;

export type LabelKey = keyof typeof LABELS;

export function leadNoteRoleLabel(role: string): string {
	const departments: Record<string, string> = {
		engineering: "工程",
		product: "产品",
		operations: "运维",
		infra: "基础设施",
		pm: "产品规划",
		content: "内容",
		life: "生活",
		growth: "增长",
		reflection: "复盘",
		xuanxue: "玄学",
	};
	return role.endsWith("-triage")
		? "分流 Lead"
		: Object.hasOwn(departments, role)
			? `${departments[role]} Lead`
			: `部门 Lead（${role}）`;
}

export function label(
	key: LabelKey,
	params: Record<string, string | number> = {},
): string {
	const template = LABELS[key];
	if (!template) throw new Error(`Unknown epic-page label: ${key}`);
	return template.replace(/\{([a-z0-9_]+)\}/g, (_match, name: string) => {
		if (!(name in params)) {
			throw new Error(`Missing epic-page label parameter: ${name}`);
		}
		return String(params[name]);
	});
}
