#!/bin/bash
# FLY-259 PR-B — codex-lead-tui-home.sh: idempotent assembly + validation of a
# Codex TUI Lead's isolated CODEX_HOME, and the remote-control daemon ensure.
#
# Usage:
#   codex-lead-tui-home.sh ensure-home   # assemble/validate $FLYWHEEL_CODEX_TUI_HOME
#   codex-lead-tui-home.sh ensure-daemon # idempotent `codex remote-control start`
#
# Contracts (plan v1.44.0 §3 D3 / §4 PR-B — review-pinned):
#   - SAFETY PIN double-insurance: config.toml carries sandbox_mode=read-only +
#     approval_policy=never (the runtime ALSO re-pins via thread params every
#     resume; the TUI command line ALSO passes explicit flags — R4 HIGH-4).
#     A pre-existing config with a DIFFERENT sandbox/approval value is a
#     fail-close exit 1 (FLY-224 HIGH-1 semantics transplanted) — we never
#     silently overwrite an operator's explicit (mis)configuration.
#   - persona does NOT live here (thread-params baseInstructions is the only
#     persona path; the demo-era AGENTS.md approach is retired — D3).
#   - standalone install REQUIRED for the daemon (npm codex has no daemon
#     backend): fail-loud with instructions, NEVER auto `curl | sh`.
#   - auth.json must exist (provisioning is the operator's/FLY-246's job).
#   - everything idempotent: re-running with a compliant home is a no-op.
#
# Env:
#   FLYWHEEL_CODEX_TUI_HOME   (required) isolated CODEX_HOME path
#   FLYWHEEL_CODEX_TUI_CWD    (required for ensure-home) Lead working dir to trust
#   FLYWHEEL_CODEX_BIN        (optional) codex binary for ensure-daemon (default: codex)

set -euo pipefail

log() { echo "[codex-lead-tui-home] $*" >&2; }
die() { log "ERROR: $*"; exit 1; }

HOME_DIR="${FLYWHEEL_CODEX_TUI_HOME:-}"
[ -n "$HOME_DIR" ] || die "FLYWHEEL_CODEX_TUI_HOME is required"

CONFIG="$HOME_DIR/config.toml"

ensure_home() {
  local cwd="${FLYWHEEL_CODEX_TUI_CWD:-}"
  [ -n "$cwd" ] || die "FLYWHEEL_CODEX_TUI_CWD is required for ensure-home"
  mkdir -p "$HOME_DIR"

  # 1. auth must be provisioned already (operator / FLY-246) — fail-loud.
  [ -f "$HOME_DIR/auth.json" ] || die "auth.json missing in $HOME_DIR — provision the Lead's Codex auth first (see FLY-246); this script never copies credentials"

  # 2. standalone install required for the daemon backend — fail-loud, no auto-install.
  local standalone="$HOME_DIR/packages/standalone/current/codex"
  if [ ! -x "$standalone" ]; then
    die "standalone codex install missing at $standalone — the remote-control daemon requires it. Install with: CODEX_HOME=$HOME_DIR sh -c 'curl -fsSL https://chatgpt.com/codex/install.sh | sh' (then REVERT any shell-profile PATH edit the installer makes — see FLY-259 spike notes)"
  fi

  # 3. config.toml: write pins if absent; FAIL-CLOSE if present with drift.
  #    Code review R1 HIGH-3: grep can be bypassed by TOML comments
  #    (`sandbox_mode = "danger-full-access" # sandbox_mode = "read-only"`) —
  #    validate EFFECTIVE values with a real TOML parser (python3.11+ tomllib;
  #    its absence is itself a fail-close).
  if [ -f "$CONFIG" ]; then
    python3 - "$CONFIG" <<'PYCHECK' || die "config.toml pin validation failed (effective values must be sandbox_mode=read-only + approval_policy=never; parse errors and tomllib absence also fail closed). Fix $CONFIG manually."
import sys
try:
    import tomllib
except ImportError:
    sys.exit(2)  # no parser → fail closed, never guess
try:
    with open(sys.argv[1], "rb") as f:
        cfg = tomllib.load(f)
except Exception:
    sys.exit(3)  # unparseable config → fail closed
ok = cfg.get("sandbox_mode") == "read-only" and cfg.get("approval_policy") == "never"
sys.exit(0 if ok else 4)
PYCHECK
  else
    cat > "$CONFIG" <<EOF
# Generated by codex-lead-tui-home.sh (FLY-259) — safety pins for a read-only
# chat-only companion TUI Lead. The runtime re-pins via thread params on every
# resume and the TUI command line carries explicit flags (double insurance).
sandbox_mode = "read-only"
approval_policy = "never"
EOF
    log "config.toml written with read-only/never pins"
  fi

  # 4. trust the Lead's working dir (kills the boot trust-menu; cwd menu is
  #    killed by -C on the TUI command — spike-verified, zero menus).
  #    Code review R2 MED-4: judge the EFFECTIVE trust state via TOML parse —
  #    grep presence would accept an explicit untrusted entry (menu stays) and
  #    can false-match on comments/metacharacters.
  local trust_state
  trust_state=$(python3 - "$CONFIG" "$cwd" <<'PYTRUST'
import sys
try:
    import tomllib
except ImportError:
    print("error"); sys.exit(0)
try:
    with open(sys.argv[1], "rb") as f:
        cfg = tomllib.load(f)
except Exception:
    print("error"); sys.exit(0)
projects = cfg.get("projects", {})
# R4 MED-1: a non-table `projects` (scalar/list) must fail closed — appending
# a [projects."<cwd>"] table next to it would produce invalid TOML.
if not isinstance(projects, dict):
    print("error"); sys.exit(0)
if sys.argv[2] not in projects:
    print("absent")  # no entry at all -> safe to append
else:
    entry = projects[sys.argv[2]]
    if not isinstance(entry, dict):
        print("error"); sys.exit(0)  # entry itself malformed -> fail closed
    level = entry.get("trust_level")
    # R3 MED-2: an EXISTING table without trust_level must NOT be appended to
    # (duplicate [projects."<cwd>"] tables are invalid TOML) -> fail loud.
    print("trusted" if level == "trusted" else ("empty" if level is None else "drift"))
PYTRUST
)
  case "$trust_state" in
    trusted) : ;;
    empty) die "config.toml has a [projects.\"$cwd\"] table without trust_level — appending would create an invalid duplicate table (R3 MED-2). Add trust_level = \"trusted\" to the existing table manually." ;;
    absent)
      cat >> "$CONFIG" <<EOF

[projects."$cwd"]
trust_level = "trusted"
EOF
      log "trusted project dir added: $cwd"
      ;;
    drift) die "config.toml has an explicit non-trusted entry for $cwd — the boot trust menu would block an unattended TUI. Fix $CONFIG manually." ;;
    *) die "trust-state TOML inspection failed for $CONFIG (parser missing or unparseable config) — fail closed" ;;
  esac

  log "home OK: $HOME_DIR"
}

ensure_daemon() {
  # Code review R1 MED-6: default to the STANDALONE binary inside this home —
  # the daemon requires it, and a PATH `codex` (npm install) would fail forever
  # even on a correctly provisioned home. Explicit override stays possible.
  local codex_bin="${FLYWHEEL_CODEX_BIN:-$HOME_DIR/packages/standalone/current/codex}"
  [ -x "$codex_bin" ] || die "codex binary not executable: $codex_bin (standalone install missing? see ensure-home)"
  # `remote-control start` is idempotent (spike-verified: already-running →
  # status connected). Fail-loud otherwise — the supervisor retries with backoff.
  CODEX_HOME="$HOME_DIR" "$codex_bin" remote-control start --json \
    || die "remote-control start failed (home: $HOME_DIR)"
  local sock="$HOME_DIR/app-server-control/app-server-control.sock"
  [ -S "$sock" ] || die "daemon reported started but control socket missing: $sock"
  log "daemon OK: $sock"
}

case "${1:-}" in
  ensure-home)   ensure_home ;;
  ensure-daemon) ensure_daemon ;;
  *) die "usage: $0 ensure-home|ensure-daemon" ;;
esac
