from pathlib import Path
from html import escape
p=Path(__file__).resolve().parent

def diagram(name):
    svg=p/(name+'.svg')
    if svg.exists(): return svg.read_text()
    return '<div class="pending"><strong>DIAGRAM PENDING LOCAL RENDER</strong><p>本机浏览器启动被系统权限限制；已按标准参数重试。流程图源码已保留，未调用远程渲染服务。</p></div><details><summary>查看 Mermaid 图源码（图形的文本定义）</summary><pre>'+escape((p/(name+'.mmd')).read_text())+'</pre></details>'

def card(key,title,body):
    return '<section class="card" data-section="'+escape(title,quote=True)+'"><h2>'+escape(title)+'</h2>'+body+'<label for="c-'+key+'">这一部分的意见</label><textarea id="c-'+key+'" data-comment="'+key+'" placeholder="输入即保存在当前浏览器"></textarea></section>'

cards=[]
cards.append(card('flow','01 · 代码已安全合入，才允许回收', '<p>worktree 是任务使用的独立工作目录；分支是这份工作的提交记录。分支改叫 docs/… 或 feat/… 后，系统仍应核实它实际合入的代码，再回收空间。</p>'+diagram('flow')+'<p>先证明所有执行体已退出，再检查目录身份。只有代码已被可信合入记录覆盖、目录干净，才执行真实删除，并读回确认。</p>'))
cards.append(card('model','02 · 记住目录身份，而不只记住名字', diagram('model')+'<dl><dt>创建代次</dt><dd>目录每次创建的唯一编号，避免同一路径重建后被误删。</dd><dt>绑定</dt><dd>任务与目录、代次和分支之间的持久记录；完成提交时核对并更新实际分支。</dd><dt>合入证明</dt><dd>来自可信仓库、同一 PR（代码合入申请）的记录，必须明确目标是 main（项目主分支）。</dd><dt>删除收据</dt><dd>记录删除前的实际提交和删除后结果；目录和分支分别计账。</dd></dl><p>旧目标快照继续有效；只在核实路径和代次相同后，用合入证明处理分支名称变化。</p>'))
cards.append(card('choice','03 · 保留安全门，补上名称变化这条路','<p><strong>采用：</strong>原路径继续通过；自起分支新增可信合入证明通路。精确等于已合入申请的提交，或证实当前提交已包含在同仓主分支，才允许继续。</p><p>绑定更新采用 CAS，即只有旧值仍与观察时一致才写入。清理本地分支也比较删除前的提交值；并发改动出现时保留分支。</p><p><strong>不采用：</strong>仅去掉名称检查会削弱保护；仅更新新绑定无法修复旧快照；禁止自起分支会改变正常工作流。</p>'))
cards.append(card('verify','04 · 验收看目录是否真的消失','<div class="tablewrap"><table><thead><tr><th>真实 Git 仓库中的场景</th><th>必须看到</th></tr></thead><tbody><tr><td>旧派生分支，原安全门通过</td><td>旧路径仍可删除</td></tr><tr><td>自起 docs 分支，代码已合入且干净</td><td>目录、Git 登记、实际分支都消失</td></tr><tr><td>自起分支尚未合入</td><td>全部保留，不能标已清理</td></tr><tr><td>已合入，但有未提交文件</td><td>全部保留，明确提示目录脏</td></tr></tbody></table></div><p>在隔离副本重现 FLY-2601 的旧绑定与实际 docs 分支差异，完整跑一次 land（合入后的收尾流程）。还需验证精确提交版本的 CI（自动检查）通过。</p><p class="notice">以上是实施与 QA 的验收要求，当前设计阶段尚未运行，不能据此声称生产问题已修复。</p>'))
cards.append(card('scope','05 · 存量只盘点，失败说清原因','<p>交付只读盘点命令，列出已合入任务的残留目录、实际分支、提交、干净状态和阻断原因，供 FLY-2628 后续处理。不会由本设计节点删除那 28 个目录；33.7 GiB 为问题提供的事故数据，本轮没有重新测量。</p><p>原因分开显示：分支未能证明已合入、目录未登记、目录脏、无法确认干净、绑定不符、删除失败。缺少证据就保留。</p><p>已不存在目录继续沿用 FLY-2616 的 absent 语义，即有证据说明目录原本就不在，不能据此擅自删除分支。新增合入证明只授权本地回收，禁止借此删除远端分支。目录已删而分支因提交变化被保留时，必须分开记录，有限重试后交 Lead 处理，不能宣称两者均已清理。部署和 Runner 退出机制不在本单扩大。</p>'))
cards.append(card('summary','意见汇总','<p>意见会按上面的标题汇总。此标记只代表页面反馈，不代表设计通过。超过约 1800 字时分段，每段都带同一个标记。</p><div id="chunks"></div><button id="copy-all" type="button">复制全部意见</button><span id="copy-status" role="status" aria-live="polite"></span>'))
style='''*{box-sizing:border-box}body{margin:0;background:#f5f5f7;color:#1d1d1f;font:16px/1.65 -apple-system,system-ui,sans-serif}main{max-width:960px;margin:auto;padding:36px 20px 64px}h1{font-size:34px;line-height:1.25;letter-spacing:-.5px;margin:12px 0}h2{font-size:23px;color:#1a365d;line-height:1.35}p{margin:12px 0}.eyebrow{color:#007aff;font-weight:650;font-size:13px}.meta{font-size:13px;color:#86868b}.lead{font-size:21px}.card{background:white;border-radius:12px;border-left:4px solid #007aff;padding:24px;margin:22px 0;box-shadow:0 2px 12px #00000008}.pending{background:#fff8eb;border:1px solid #ff9500;border-radius:9px;padding:20px;color:#805600}.pending strong{font-size:15px}label{display:block;margin-top:22px;font-size:14px;color:#666}textarea{display:block;width:100%;min-height:82px;margin-top:7px;padding:12px;border:1px solid #d2d2d7;border-radius:8px;resize:vertical;font:inherit}textarea:focus{outline:2px solid #007aff}button{background:#007aff;color:white;border:0;border-radius:8px;padding:10px 16px;margin:8px 8px 8px 0;font:inherit;cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f5f7;padding:14px;border-radius:8px;font:13px/1.6 monospace}svg{max-width:100%;height:auto}table{border-collapse:collapse;width:100%;font-size:15px}th,td{padding:12px;text-align:left;border-bottom:1px solid #e5e5e7}dt{font-weight:650;color:#1a365d}dd{margin:0 0 12px}.notice{color:#805600;background:#fff8eb;padding:12px;border-radius:8px}.tablewrap{overflow-x:auto}#copy-status{font-size:14px;color:#666}a{color:#007aff}@media(max-width:600px){main{padding:22px 12px}h1{font-size:28px}.card{padding:18px}h2{font-size:21px}}'''
html='<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FLY-2664 · 已合入代码的目录回收</title><style>'+style+'</style></head><body><main><header><div class="eyebrow">FLY-2664 · 工程设计</div><h1>改过分支名，合入后也要能回收</h1><div class="meta">Issue: FLY-2664<br>日期: 2026-09-17<br>基于: plan.md</div><p class="lead">核实代码已经合入、目录身份正确且没有未提交改动后，真正删除任务目录和实际分支。</p><p class="meta">R1 设计评审已通过 · 非阻断实施补充已记录 · 尚未生产验证</p></header>'+''.join(cards)+'</main><script nonce="__CSP_NONCE__">'+(p/'evidence/comments-script.js').read_text()+'</script></body></html>'
(p/'founder-design.html').write_text(html)
