import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { epicShapeSnapshot, v3ItemFacts } from "../../../packages/teamlead/src/epic-page/__tests__/fixtures/epic-shape.js";
import { generateEpicPage } from "../../../packages/teamlead/src/epic-page/generate.js";
import { renderEpicPageBundle } from "../../../packages/teamlead/src/epic-page/render-html.js";
import { injectHeadMeta } from "../../../packages/teamlead/src/bridge/report-registry.js";
const directory=process.argv[2]??"/tmp/fly2557-intake-visual";
await mkdir(directory,{recursive:true});
const now=new Date();
const snapshot=epicShapeSnapshot();
snapshot.fetchedAt=now.toISOString();
const root=snapshot.roots.find(r=>r.identifier==="EPX-200")!;
root.title="测试 Epic：等待拆解";
root.hasChildIssues=false;root.startedAt=snapshot.fetchedAt;
const intake={eventUid:`epic_intake:${root.id}:${snapshot.fetchedAt}`,issueUuid:root.id,identifier:root.identifier,startedAt:snapshot.fetchedAt,intakeAt:snapshot.fetchedAt,observedAt:snapshot.fetchedAt,projectName:"example",leadId:"test-lead",bindingDigest:"fixture",sourceSpanIds:["fixture-span"],backfill:false,active:true,workState:"pending" as const,leadEventSeq:1,pageDirty:true,result:null};
const page=generateEpicPage({snapshot,itemFacts:v3ItemFacts(snapshot),now,projectName:"example",trigger:"scan",intakes:[intake]});
const bundle=renderEpicPageBundle(page,now);
if(!bundle.html.includes("待拆解（intake 于"))throw new Error("pending card missing");
const html=injectHeadMeta(bundle.html,()=>"fly2557syntheticnonce");
if(html.includes("__CSP_NONCE__")||!html.includes("'nonce-fly2557syntheticnonce'"))throw new Error("CSP nonce mismatch");
if(/<(?:script|link|img)\b[^>]*(?:src|href)=["']https?:/i.test(html))throw new Error("external resource");
await writeFile(join(directory,"intake.html"),html);
await writeFile(join(directory,"intake.json"),JSON.stringify(page,null,2));
console.log(JSON.stringify({directory,bytes:Buffer.byteLength(html),generatedAt:page.generated_at,cspNonce:"matched",externalResources:0,source:"synthetic fixture only"}));
