#!/bin/bash
# FLY-519: shared sanitization for fleet capture/provision.
#
# Two responsibilities, both in service of the red line "capture artifacts that
# get committed to git must contain ZERO secrets":
#   - redact_env_to_keys: turn a real ~/.flywheel/.env into a key-name-only
#     .env.example (never writes a value).
#   - scan_for_secrets: a defence-in-depth net that fails (non-zero) if any
#     secret-looking value is present in a path. Run as the final gate of
#     fleet-capture.sh and as a standalone validator.
#
# Sourceable (guarded) so capture + tests can use the functions directly.
[ -n "${FLEET_SANITIZE_SOURCED:-}" ] && return 0
FLEET_SANITIZE_SOURCED=1

# ──────────────────────────────────────────────────────────────────────────
# redact_env_to_keys <env-file> <out-file>
#   Treats the WHOLE source .env as tainted. Emits a SAFE SYNTHETIC header +
#   ONLY recognized assignment key names (KEY=, export KEY=) — every value is
#   dropped, and ALL source comments, blank lines, and unrecognized lines are
#   dropped too (never copied verbatim: an operator may hide a secret in a
#   comment, and a low-entropy one would slip the scanner).
# ──────────────────────────────────────────────────────────────────────────
redact_env_to_keys() {
  local in="$1" out="$2"
  if [ -z "$in" ] || [ -z "$out" ]; then
    echo "redact_env_to_keys: usage: redact_env_to_keys <env-file> <out-file>" >&2
    return 2
  fi
  if [ ! -f "$in" ]; then
    echo "redact_env_to_keys: input not found: $in" >&2
    return 2
  fi
  # Treat the ENTIRE source .env as tainted (Codex design-review HIGH): emit a
  # SAFE SYNTHETIC header + ONLY recognized assignment KEY names. Source
  # comments are DROPPED, never copied — an operator may have written a secret
  # (a low-entropy password, a recovery code) in a comment, and copying it
  # verbatim would leak it through the sanctioned capture path.
  {
    printf '# fleet env.example — KEY NAMES ONLY (generated by fleet-capture.sh).\n'
    printf '# Zero values. Fill the real values on the target host; provisioning\n'
    printf '# never writes them. Source comments are intentionally NOT preserved.\n'
  } > "$out"
  local line exp key
  while IFS= read -r line || [ -n "$line" ]; do
    # Recognize only: [indent](export )?KEY=... — emit the key name, no value,
    # no indent, no surrounding context.
    if [[ "$line" =~ ^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)= ]]; then
      exp=""
      [ -n "${BASH_REMATCH[1]}" ] && exp="export "
      key="${BASH_REMATCH[2]}"
      printf '%s%s=\n' "$exp" "$key" >> "$out"
    fi
    # everything else (comments, blanks, unrecognized) → dropped.
  done < "$in"
  return 0
}

# ──────────────────────────────────────────────────────────────────────────
# _fleet_token_is_secret <token-run>
#   Given a single opaque token run (>=16 chars, already extracted by the
#   caller), return 0 if it looks like a real secret, 1 otherwise. NOT a
#   secret if it is a token ENV *name* reference (SCREAMING_SNAKE), a decimal
#   id (snowflake/channel), or a known placeholder token.
# ──────────────────────────────────────────────────────────────────────────
_fleet_token_is_secret() {
  local core="$1"
  case "$core" in
    *__PLACEHOLDER__*|*CHANGE_ME*|*CHANGEME*|*REPLACE_ME*|*placeholder*) return 1 ;;
  esac
  # SCREAMING_SNAKE identifier → an env-name reference (legit), not a secret.
  [[ "$core" =~ ^[A-Z][A-Z0-9_]*$ ]] && return 1
  # pure decimal → a snowflake / channel id, not a secret.
  [[ "$core" =~ ^[0-9]+$ ]] && return 1
  return 0
}

# _fleet_vendor_re — the unambiguous vendor-token regex set (shared by
# scan_for_secrets and scan_code_tree_for_secrets; FLY-1062 refactor — the
# pattern list is byte-identical to the original in-function array).
_fleet_vendor_re() {
  local -a vendor=(
    'mfa\.[A-Za-z0-9_-]{20,}'
    '[MNO][A-Za-z0-9_-]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27,}'
    'xox[baprs]-[A-Za-z0-9-]{10,}'
    'sk-(proj-)?[A-Za-z0-9_-]{20,}'
    'gh[pousr]_[A-Za-z0-9]{30,}'
    'github_pat_[A-Za-z0-9_]{30,}'
    'AKIA[0-9A-Z]{16}'
    'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{6,}'
    'fwk_[0-9a-f]{32,}'
  )
  (IFS='|'; printf '%s' "${vendor[*]}")
}

# ──────────────────────────────────────────────────────────────────────────
# scan_code_tree_for_secrets <tree-dir>
#   FLY-1062: secret net for a RELEASE CODE TREE (the packaged payload).
#   scan_for_secrets' Layer 2 is calibrated for small config artifacts and
#   floods on ordinary code identifiers (camelCase `tokenEnvName` etc.), so a
#   code tree gets:
#     • Layer 1 (vendor tokens)      — whole tree, unambiguous formats;
#     • Layer 3 (high-entropy blobs) — whole tree;
#     • FULL scan_for_secrets        — config-class files only (.env*, json,
#       plist, yaml/yml, toml), where a raw KEY=value leak would live.
#   Returns 0 clean / 1 findings / 2 usage.
# ──────────────────────────────────────────────────────────────────────────
scan_code_tree_for_secrets() {
  local tree="$1"
  [ -d "$tree" ] || { echo "scan_code_tree_for_secrets: not a dir: $tree" >&2; return 2; }
  local hits=0

  # Layer 1: vendor tokens anywhere. grep exit 1 = clean no-match; exit >1 = a
  # TOOL error (unreadable file, bad pattern) — that must return 2, never read
  # as "clean" (FLY-1062 content gate Codex R4: an incompletely scanned tree is
  # not a scanned tree).
  local v1 st1=0
  v1="$(grep -rEnI "$(_fleet_vendor_re)" "$tree" 2>/dev/null)" || st1=$?
  if [ "$st1" -gt 1 ]; then
    echo "scan_code_tree_for_secrets: [scan-error] vendor grep failed (exit $st1)" >&2
    return 2
  fi
  if [ -n "$v1" ]; then
    hits=1
    echo "scan_code_tree_for_secrets: [vendor-token] (redacted):" >&2
    printf '%s\n' "$v1" | sed -E 's/([A-Za-z0-9_+/=.-]{8})[A-Za-z0-9_+/=.-]{4,}/\1…REDACTED…/g' >&2
  fi

  # Layer 3: high-entropy bare blob (>=40 chars, mixed upper+lower+digit).
  # Same tool-error discipline as Layer 1.
  local he row token he_hit="" st3=0
  he="$(grep -rEnoI '[A-Za-z0-9_-]{40,}' "$tree" 2>/dev/null)" || st3=$?
  if [ "$st3" -gt 1 ]; then
    echo "scan_code_tree_for_secrets: [scan-error] entropy grep failed (exit $st3)" >&2
    return 2
  fi
  while IFS= read -r row; do
    [ -z "$row" ] && continue
    token="${row#*:}"; token="${token#*:}"
    if [[ "$token" =~ [a-z] ]] && [[ "$token" =~ [A-Z] ]] && [[ "$token" =~ [0-9] ]]; then
      he_hit+="$row"$'\n'
    fi
  done <<< "$he"
  if [ -n "$he_hit" ]; then
    hits=1
    echo "scan_code_tree_for_secrets: [high-entropy] (redacted):" >&2
    printf '%s' "$he_hit" | sed -E 's/([A-Za-z0-9_+/=.-]{8})[A-Za-z0-9_+/=.-]{4,}/\1…REDACTED…/g' >&2
  fi

  # Config-class files get the full net (incl. the assignment layer). A find
  # failure means the enumeration is incomplete — tool error, return 2.
  local -a cfg=()
  local find_out st4=0
  find_out="$(find "$tree" -type f \( -name "*.env" -o -name ".env*" -o -name "*.json" -o -name "*.plist" -o -name "*.yaml" -o -name "*.yml" -o -name "*.toml" \) 2>/dev/null)" || st4=$?
  if [ "$st4" -ne 0 ]; then
    echo "scan_code_tree_for_secrets: [scan-error] find failed (exit $st4)" >&2
    return 2
  fi
  while IFS= read -r f; do
    [ -n "$f" ] && cfg+=("$f")
  done <<< "$find_out"
  if [ "${#cfg[@]}" -gt 0 ]; then
    # propagate the full net's tool errors (2) distinctly from hits (1)
    local sfs_rc=0
    scan_for_secrets "${cfg[@]}" || sfs_rc=$?
    if [ "$sfs_rc" -ge 2 ]; then
      echo "scan_code_tree_for_secrets: [scan-error] config-class net failed (exit $sfs_rc)" >&2
      return 2
    fi
    [ "$sfs_rc" -eq 1 ] && hits=1
  fi

  return "$hits"
}

# ──────────────────────────────────────────────────────────────────────────
# scan_for_secrets <path...>
#   Recursively scans files for secret-looking content. Returns:
#     0 = clean, 1 = secret(s) found, 2 = usage OR scan-tool error (an input
#     that could not be fully scanned is never reported clean — fail-closed).
#   Found locations are printed to stderr with the value redacted.
#
# Three layers (defence in depth):
#   1. Bare vendor token patterns (unambiguous: sk-, ghp_, xox, JWT, Discord,
#      AWS) — flagged anywhere, including inside JSON.
#   2. Shell assignment `[(export )]KEY=value` where KEY looks secret-named and
#      the value is non-empty and not a placeholder. Catches a leaked raw .env
#      whose value isn't a recognized vendor format.
#   3. High-entropy bare blob (>=40 chars, mixed upper+lower+digit). Catches a
#      bare custom token that has no vendor prefix.
#
# Deliberately NOT flagged (legit capture content): token ENV *names*
# (SCREAMING_SNAKE identifiers), decimal Discord channel IDs, repo URLs,
# booleans, placeholders. These keep the net from blocking real captures.
# ──────────────────────────────────────────────────────────────────────────
scan_for_secrets() {
  if [ "$#" -lt 1 ]; then
    echo "scan_for_secrets: usage: scan_for_secrets <path...>" >&2
    return 2
  fi
  local p
  for p in "$@"; do
    if [ ! -e "$p" ]; then
      echo "scan_for_secrets: path not found: $p" >&2
      return 2
    fi
  done

  local hits=0
  local matches=""

  # ── Layer 1: bare vendor token patterns ─────────────────────────────────
  # grep exit 1 = clean no-match; >1 = TOOL error → return 2, never "clean"
  # (FLY-1062 Codex R5: an incompletely scanned input is not a scanned input).
  local vendor_re
  vendor_re="$(_fleet_vendor_re)"
  local v1 sfs1=0
  v1="$(grep -rEnI "$vendor_re" "$@" 2>/dev/null)" || sfs1=$?
  if [ "$sfs1" -gt 1 ]; then
    echo "scan_for_secrets: [scan-error] vendor grep failed (exit $sfs1)" >&2
    return 2
  fi
  if [ -n "$v1" ]; then
    hits=1
    matches+="[vendor-token]"$'\n'"$v1"$'\n'
  fi

  # ── Layer 2: a secret-named key adjacent to a real secret value ──────────
  # Matches shell (KEY=val), JSON ("key": "val"), yaml (key: val), and comment
  # (# KEY=val) forms, CASE-INSENSITIVE on the key name (catches camelCase
  # apiKey / botToken). On each candidate line we check EVERY opaque token run
  # (not just the value after the first separator) — so a real secret hiding
  # behind a leading env-name on a minified multi-field JSON line is still
  # caught (Codex R2 HIGH). A run is a secret unless it's a token ENV *name*
  # reference (SCREAMING_SNAKE), a decimal id, or a placeholder. Errs toward
  # over-flagging (safe direction for a net). projects.json is additionally
  # normalized to one-field-per-line by fleet-capture.sh (jq) so the common
  # path never relies on multi-field line parsing.
  local kv_keyre='[A-Za-z0-9_]*(token|secret|password|passwd|apikey|api[_-]?key|privkey|private[_-]?key|access[_-]?key|auth[_-]?token|credential|[_-]key)[A-Za-z0-9_]*'
  local cand sfs2=0
  cand="$(grep -rEnIi "${kv_keyre}[\"' ]*[:=]" "$@" 2>/dev/null)" || sfs2=$?
  if [ "$sfs2" -gt 1 ]; then
    echo "scan_for_secrets: [scan-error] assignment grep failed (exit $sfs2)" >&2
    return 2
  fi
  if [ -n "$cand" ]; then
    local kv_hit="" row content tok
    while IFS= read -r row; do
      [ -z "$row" ] && continue
      # row = "file:line:content" — strip the grep prefix (2 colons).
      content="${row#*:}"; content="${content#*:}"
      while IFS= read -r tok; do
        [ -z "$tok" ] && continue
        if _fleet_token_is_secret "$tok"; then
          kv_hit+="$row"$'\n'
          break
        fi
      done < <(printf '%s' "$content" | grep -oE '[A-Za-z0-9+/_-]{16,}')
    done <<< "$cand"
    if [ -n "$kv_hit" ]; then
      hits=1
      matches+="[secret-assignment]"$'\n'"$kv_hit"
    fi
  fi

  # ── Layer 3: high-entropy bare blob ─────────────────────────────────────
  # A run of >=40 chars from the base64url/token alphabet that contains at least
  # one lowercase, one uppercase, AND one digit. Excludes SCREAMING_SNAKE env
  # names (no lowercase), git SHAs (no uppercase), channel IDs (digits only).
  # NOTE: the alphabet deliberately omits '/', '+', '=' so filesystem PATHS
  # (e.g. projectRoot absolute paths) break at slashes and never form one long
  # run — paths are not secrets. Vendor base64 tokens with '/+=' are already
  # covered by Layer 1; the main leak vector (a raw .env value) by Layer 2.
  local he sfs3=0
  he="$(grep -rEnoI '[A-Za-z0-9_-]{40,}' "$@" 2>/dev/null)" || sfs3=$?
  if [ "$sfs3" -gt 1 ]; then
    echo "scan_for_secrets: [scan-error] entropy grep failed (exit $sfs3)" >&2
    return 2
  fi
  if [ -n "$he" ]; then
    local he_hit=""
    local row token
    while IFS= read -r row; do
      [ -z "$row" ] && continue
      # row is "file:line:MATCH"; token is everything after the 2nd colon.
      token="${row#*:}"; token="${token#*:}"
      if [[ "$token" =~ [a-z] ]] && [[ "$token" =~ [A-Z] ]] && [[ "$token" =~ [0-9] ]]; then
        he_hit+="$row"$'\n'
      fi
    done <<< "$he"
    if [ -n "$he_hit" ]; then
      hits=1
      matches+="[high-entropy]"$'\n'"$he_hit"
    fi
  fi

  if [ "$hits" -ne 0 ]; then
    {
      echo "scan_for_secrets: SECRET-LIKE CONTENT FOUND (redacted):"
      printf '%s\n' "$matches" | sed -E 's/([A-Za-z0-9_+/=.-]{8})[A-Za-z0-9_+/=.-]{4,}/\1…REDACTED…/g'
    } >&2
    return 1
  fi
  return 0
}

# ──────────────────────────────────────────────────────────────────────────
# scan_string_for_secrets <string>
#   FLY-1023 M0: single-VALUE form of scan_for_secrets for callers that hold
#   a candidate string in memory (buddy journal keys, support summaries).
#   Implemented by spooling the value to a 0600 temp file and running the
#   EXACT same path-based scanner — one pattern set, zero drift. Returns the
#   same codes: 0 = clean, 1 = secret-like, 2 = usage error.
# ──────────────────────────────────────────────────────────────────────────
scan_string_for_secrets() {
  if [ "$#" -ne 1 ]; then
    echo "scan_string_for_secrets: usage: scan_string_for_secrets <string>" >&2
    return 2
  fi
  local tmp rc
  tmp="$(mktemp "${TMPDIR:-/tmp}/fleet-scan-str.XXXXXX")" || return 2
  chmod 600 "$tmp" || { rm -f "$tmp"; return 2; }
  printf '%s\n' "$1" > "$tmp"
  scan_for_secrets "$tmp"
  rc=$?
  rm -f "$tmp"
  return $rc
}
