#!/usr/bin/env bash
# FLY-1189 H1: pure, sourceable helpers for the multi-Lead ADDITIVE extension
# of scripts/test-deploy.sh / scripts/test-teardown.sh (single Bridge, ≥2 real
# test Leads — the N-to-N topology PR-C QA needs). Same hermetic-lib pattern
# as scripts/lib/qa-room.sh: no IO of its own beyond the paths passed in, so
# every function is unit-testable with temp fixtures.
#
# CANONICAL QA CONTRACT: every synthetic Lead must satisfy the current closed
# registry schema. QA Leads are summary-exempt, so a 529 room can exercise its
# target behavior without creating Raya summary PRs. Guarded by
# scripts/__tests__/test-deploy-multilead.test.sh (A1-A3 + FLY-2030 B1).

# ── FLYWHEEL_PROJECTS builder ──────────────────────────────────────────────
# Args: projectName projectRoot projectRepo agentId chatChannel botTokenEnv
#       slotRole mainLabelsJson extraLeadsJson [botUserId discordStateDir]
# mainLabelsJson defaults to ["*"] (legacy); extraLeadsJson is an array of
# {agentId, chatChannel|chatChannel-bearing fields, botTokenEnv/tokenEnvVar,
#  labels:[...]} entries produced by qa_multilead_validate_campaign_args.
qa_multilead_build_projects() {
	local project_name="$1" project_root="$2" project_repo="$3" agent_id="$4"
	local chat_channel="$5" bot_token_env="$6" slot_role="$7"
	local main_labels_json="${8:-[\"*\"]}" extra_leads_json="${9:-[]}"
	local bot_user_id="${10:-}" discord_state_dir="${11:-}"
	jq -n \
		--arg projectName "$project_name" \
		--arg projectRoot "$project_root" \
		--arg projectRepo "$project_repo" \
		--arg agentId "$agent_id" \
		--arg chatChannel "$chat_channel" \
		--arg botTokenEnv "$bot_token_env" \
		--arg slotRole "$slot_role" \
		--arg botUserId "$bot_user_id" \
		--arg discordStateDir "$discord_state_dir" \
		--argjson mainLabels "$main_labels_json" \
		--argjson extraLeads "$extra_leads_json" \
		'
  [
    ({
      projectName: $projectName,
      projectRoot: $projectRoot,
      projectRepo: $projectRepo,
      leads: ([
        ({
          agentId: $agentId,
          summaryRole: "exempt",
          chatChannel: $chatChannel,
          botTokenEnv: $botTokenEnv,
          match: { labels: $mainLabels }
        } | if $botUserId != "" then . + {
          botUserId: $botUserId,
          discordStateDir: $discordStateDir
        } else . end)
      ] + ($extraLeads | map(. as $lead |
        ({
          agentId: $lead.agentId,
          summaryRole: "exempt",
          chatChannel: $lead.chatChannel,
          botTokenEnv: $lead.tokenEnvVar,
          match: { labels: $lead.labels }
        } | if $botUserId != "" then . + {
          botUserId: $lead.botAppId,
          discordStateDir: $lead.discordStateDir
        } else . end)
      )))
    })
    | if $slotRole == "cos" then . + { generalChannel: $chatChannel } else . end
  ]
  '
}

# ── Canonical sandbox config.yaml ──────────────────────────────────────────
# Args: projectName [generalized]
qa_multilead_config_yaml() {
	local TEST_PROJECT_NAME="$1"
	local mode="${2:-ordinary}"
	if [[ "$mode" != "ordinary" && "$mode" != "generalized" ]]; then
		echo "[qa-multilead] config mode must be ordinary or generalized" >&2
		return 1
	fi
	cat <<EOF
# Generated by scripts/test-deploy.sh (FLY-115 v1.24.3) — sandbox test config.
# DO NOT commit to xrliAnnie/flywheel-qa-sandbox; teardown wipes HOST_REPO.
project: ${TEST_PROJECT_NAME}

linear:
  team_id: FLY

runners:
  default: claude
  available:
    claude:
      type: claude
      model: sonnet

teams:
  - name: default
    orchestrators:
      - type: dag
        runner: claude

decision_layer:
  autonomy_level: advisor
  escalation_channel: discord

doc_flow:
  default_department: engineering

checkpoints:
  approve_to_ship:
    timeout_ms: 14400000     # 4h (FLY-159: ConfigLoader floor; anything lower is warn+raised)
    timeout_behavior: fail-close
EOF
}

# ── Validators ─────────────────────────────────────────────────────────────
# "<slotId>:<deptLabel>" → "slotId deptLabel". Label charset is restricted to
# what Linear labels + YAML + jq --arg all pass through safely.
qa_multilead_parse_spec() {
	local spec="${1:-}"
	if [[ "$spec" =~ ^([1-9][0-9]*):([A-Za-z0-9._-]+)$ ]]; then
		echo "${BASH_REMATCH[1]} ${BASH_REMATCH[2]}"
		return 0
	fi
	echo "[qa-multilead] invalid --extra-lead spec '${spec}' (expected <slotId>:<deptLabel>, label charset [A-Za-z0-9._-])" >&2
	return 1
}

# Resolve one slot's fields from test-slots.json. Fails loud when the slot is
# missing or any required field is null/empty (identitySource stays optional —
# legacy role fallback applies downstream).
qa_multilead_slot_fields() {
	local slots_file="$1" slot="$2"
	local idx=$((slot - 1))
	local json
	json=$(jq -e ".slots[${idx}] // empty | {agentId: .botName, botAppId: .botAppId, tokenEnvVar: .tokenEnvVar, chatChannel: .channelId, role: .role, identitySource: (.identitySource // \"\")}" "$slots_file" 2>/dev/null) || {
		echo "[qa-multilead] slot ${slot} not found in ${slots_file}" >&2
		return 1
	}
	local field value
	for field in agentId botAppId tokenEnvVar chatChannel role; do
		value=$(jq -r ".${field} // empty" <<<"$json")
		if [[ -z "$value" || "$value" == "null" ]]; then
			echo "[qa-multilead] slot ${slot}: field '${field}' missing or null in ${slots_file}" >&2
			return 1
		fi
	done
	echo "$json"
}

# Validate the whole --extra-lead request BEFORE any expensive work.
# Args: slotsFile mode mainSlot spec...
# stdout: extraLeads JSON array, each entry = slot fields + slotId + deptLabel
#         + labels:[deptLabel] (feeds qa_multilead_build_projects directly).
qa_multilead_validate_campaign_args() {
	local slots_file="$1" mode="$2" main_slot="$3"
	shift 3
	if [[ "$mode" != "slot" ]]; then
		echo "[qa-multilead] --extra-lead is only supported with --mode slot (got '${mode}')" >&2
		return 1
	fi
	if [[ -z "$main_slot" ]]; then
		echo "[qa-multilead] --extra-lead requires an EXPLICIT main slot number argument (auto-allocation is ambiguous for a campaign)" >&2
		return 1
	fi
	local out="[]" seen=" ${main_slot} " spec parsed slot label fields
	for spec in "$@"; do
		parsed=$(qa_multilead_parse_spec "$spec") || return 1
		slot="${parsed%% *}"
		label="${parsed#* }"
		if [[ "$seen" == *" ${slot} "* ]]; then
			echo "[qa-multilead] slot ${slot} appears more than once across main + --extra-lead" >&2
			return 1
		fi
		fields=$(qa_multilead_slot_fields "$slots_file" "$slot") || return 1
		out=$(jq --argjson f "$fields" --arg label "$label" --argjson sid "$slot" \
			'. + [$f + {slotId: $sid, deptLabel: $label, labels: [$label]}]' <<<"$out")
		seen="${seen}${slot} "
	done
	echo "$out"
}

# ── Slot lock lifecycle (campaign claim set + borrowed-lock semantics) ─────
# Sidecar file <lock>/campaign.json marks a lock as part of a multi-lead
# campaign: {ownerSlot, campaignId, borrowed}. borrowed=true means "this
# slot's Lead resources live in the OWNER slot's SLOT_DIR — the ONLY legal
# release path is the owner slot's teardown".

# rc0 + echoes ownerSlot when the lock carries a borrowed=true sidecar.
qa_multilead_lock_is_borrowed() {
	local lockdir="$1"
	local sidecar="${lockdir}/campaign.json"
	[[ -f "$sidecar" ]] || return 1
	local borrowed owner
	borrowed=$(jq -r '.borrowed // false' "$sidecar" 2>/dev/null || echo "false")
	[[ "$borrowed" == "true" ]] || return 1
	owner=$(jq -r '.ownerSlot // empty' "$sidecar" 2>/dev/null || echo "")
	echo "$owner"
	return 0
}

_qa_multilead_mtime() {
	stat -f %m "$1" 2>/dev/null || stat -c %Y "$1" 2>/dev/null || echo "0"
}

# Claim ONE slot lock. Mirrors test-deploy.sh claim_slot() semantics
# (mkdir-based, stale "claiming" >300s reclaim, dead-PID reclaim via the
# provided stale command) with one hardening on top: a BORROWED lock is NEVER
# reclaimed here — dead or alive — because its resources belong to the owner
# slot's campaign; reclaiming it would run this slot's teardown against
# another slot's live Lead. Fail loud and point at the owner instead.
# Args: lockdir staleCmd slotArg   (staleCmd "" → no stale teardown, plain refuse)
qa_multilead_claim_one() {
	local lockfile="$1" stale_cmd="${2:-}" slot_arg="${3:-}"
	if mkdir "$lockfile" 2>/dev/null; then
		echo "claiming" >"$lockfile/pid"
		return 0
	fi
	local owner
	if owner=$(qa_multilead_lock_is_borrowed "$lockfile"); then
		echo "[qa-multilead] ${lockfile} is BORROWED by campaign owner slot ${owner} — not reclaiming; run test-teardown.sh ${owner} first" >&2
		return 1
	fi
	local lock_pid
	lock_pid=$(cat "$lockfile/pid" 2>/dev/null || echo "")
	if [[ "$lock_pid" == "cycle-failed" ]]; then
		echo "[qa-multilead] ${lockfile} has cycle-failed ownership — not reclaiming; run explicit test-teardown.sh ${slot_arg}" >&2
		return 1
	fi
	if [[ "$lock_pid" == "claiming" ]]; then
		local lock_age
		lock_age=$(($(date +%s) - $(_qa_multilead_mtime "$lockfile/pid")))
		if ((lock_age > 300)); then
			if [[ -n "$stale_cmd" ]]; then
				"$stale_cmd" "$slot_arg" || echo "[qa-multilead] WARN: stale teardown for slot ${slot_arg} reported errors — continuing" >&2
			fi
			mkdir "$lockfile" 2>/dev/null || return 1
			echo "claiming" >"$lockfile/pid"
			return 0
		fi
		return 1
	fi
	if [[ -n "$lock_pid" ]] && ! kill -0 "$lock_pid" 2>/dev/null; then
		if [[ -n "$stale_cmd" ]]; then
			"$stale_cmd" "$slot_arg" || echo "[qa-multilead] WARN: stale teardown for slot ${slot_arg} reported errors — continuing" >&2
		fi
		mkdir "$lockfile" 2>/dev/null || return 1
		echo "claiming" >"$lockfile/pid"
		return 0
	fi
	return 1
}

# Atomically claim a SET of slots (sorted ascending so concurrent campaigns
# can't deadlock on claim order). Any single failure → every lock newly
# claimed by THIS call is released → rc1 (zero side effects).
# stdout on success: the claimed lockdirs, one per line, in claim order.
# Args: lockRoot staleCmd slot...
qa_multilead_claim_set() {
	local lock_root="$1" stale_cmd="$2"
	shift 2
	local sorted
	sorted=$(printf '%s\n' "$@" | sort -n)
	local claimed=() s lockdir c
	while IFS= read -r s; do
		[[ -z "$s" ]] && continue
		lockdir="${lock_root}/flywheel-test-slot-${s}.lock"
		if qa_multilead_claim_one "$lockdir" "$stale_cmd" "$s"; then
			claimed+=("$lockdir")
		else
			echo "[qa-multilead] slot ${s} claim failed — rolling back ${#claimed[@]} already-claimed lock(s)" >&2
			for c in ${claimed[@]+"${claimed[@]}"}; do
				rm -rf "$c"
			done
			return 1
		fi
	done <<<"$sorted"
	printf '%s\n' ${claimed[@]+"${claimed[@]}"}
	return 0
}

# Write the long-lived Bridge PID + campaign sidecar into EVERY campaign lock
# (owner + borrowed). This is what protects borrowed locks from the >300s
# stale-claiming reclaim in other deploys (the PID is alive for the whole
# campaign). Verifies each write by reading it back; any failure → rc1 (the
# caller must treat the deploy as failed and roll back).
# Args: lockRoot bridgePid ownerSlot campaignId slot...
qa_multilead_finalize_locks() {
	local lock_root="$1" bridge_pid="$2" owner_slot="$3" campaign_id="$4"
	shift 4
	local s lockdir borrowed
	for s in "$@"; do
		lockdir="${lock_root}/flywheel-test-slot-${s}.lock"
		if [[ ! -d "$lockdir" ]]; then
			echo "[qa-multilead] finalize: lock ${lockdir} missing" >&2
			return 1
		fi
		echo "$bridge_pid" >"${lockdir}/pid" || return 1
		if [[ "$(cat "${lockdir}/pid" 2>/dev/null)" != "$bridge_pid" ]]; then
			echo "[qa-multilead] finalize: pid write-back verify failed for ${lockdir}" >&2
			return 1
		fi
		if [[ "$s" != "$owner_slot" ]]; then borrowed=true; else borrowed=false; fi
		jq -n --arg owner "$owner_slot" --arg cid "$campaign_id" --argjson b "$borrowed" \
			'{ownerSlot: ($owner | tonumber), campaignId: $cid, borrowed: $b}' \
			>"${lockdir}/campaign.json" || {
			echo "[qa-multilead] finalize: sidecar write failed for ${lockdir}" >&2
			return 1
		}
	done
	return 0
}

# ── Campaign teardown (manifest-driven) ────────────────────────────────────
# Consume ${SLOT_DIR}/campaign-manifest.json: stop every extra Lead's
# supervisor, kill its tmux window, and remove its pid/session-id/manifest/
# workspace residue. Absolute paths come from the manifest (written by
# test-deploy at start), so this needs no HOME/env reconstruction.
qa_multilead_teardown_extra_leads() {
	local manifest="$1"
	[[ -f "$manifest" ]] || return 0
	local count i pid_file session_file lead_manifest workspace window pid waited
	count=$(jq '.extraLeads | length' "$manifest" 2>/dev/null || echo 0)
	for ((i = 0; i < count; i++)); do
		pid_file=$(jq -r ".extraLeads[${i}].pidFile // empty" "$manifest")
		session_file=$(jq -r ".extraLeads[${i}].sessionIdFile // empty" "$manifest")
		lead_manifest=$(jq -r ".extraLeads[${i}].leadManifest // empty" "$manifest")
		workspace=$(jq -r ".extraLeads[${i}].leadWorkspace // empty" "$manifest")
		window=$(jq -r ".extraLeads[${i}].tmuxWindow // empty" "$manifest")

		if [[ -n "$pid_file" && -f "$pid_file" ]]; then
			pid=$(cat "$pid_file" 2>/dev/null || echo "")
			if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
				echo "[qa-multilead] stopping extra-Lead supervisor PID ${pid} (SIGTERM)" >&2
				kill "$pid" 2>/dev/null || true
				waited=0
				while kill -0 "$pid" 2>/dev/null && ((waited < 10)); do
					sleep 1
					waited=$((waited + 1))
				done
				if kill -0 "$pid" 2>/dev/null; then
					echo "[qa-multilead] supervisor ${pid} survived SIGTERM; SIGKILL" >&2
					kill -9 "$pid" 2>/dev/null || true
				fi
			fi
			rm -f "$pid_file"
		fi

		if [[ -n "$window" ]] && tmux has-session -t "flywheel" 2>/dev/null; then
			if tmux list-windows -t "flywheel" -F '#{window_name}' 2>/dev/null | grep -q "^${window}$"; then
				echo "[qa-multilead] killing extra-Lead tmux window: ${window}" >&2
				tmux kill-window -t "flywheel:${window}" 2>/dev/null || true
			fi
		fi

		[[ -n "$session_file" ]] && rm -f "$session_file"
		[[ -n "$lead_manifest" ]] && rm -f "$lead_manifest"
		[[ -n "$workspace" && -d "$workspace" ]] && rm -rf "$workspace"
	done
	return 0
}

# Release the borrowed slot locks listed in the campaign manifest. Owner
# teardown ONLY — the borrowed slots own no resources of their own (everything
# lives in the owner SLOT_DIR), so releasing the lock is the whole cleanup.
# Args: manifestFile lockRoot
qa_multilead_release_borrowed_locks() {
	local manifest="$1" lock_root="$2"
	[[ -f "$manifest" ]] || return 0
	local s
	while IFS= read -r s; do
		[[ -z "$s" ]] && continue
		rm -rf "${lock_root}/flywheel-test-slot-${s}.lock"
		echo "[qa-multilead] released borrowed slot ${s} lock" >&2
	done < <(jq -r '.borrowedSlots[]?' "$manifest" 2>/dev/null || true)
	return 0
}

# ── Launch manifest (S0's flag ground truth — no secrets) ──────────────────
# macOS `ps eww` cannot read another process's env (SIP), so the deploy-time
# record IS the flag evidence: the values below are read from the CURRENT
# process env (test-deploy exports them to the Bridge via env inheritance)
# at the moment the Bridge is forked. Token env VALUES are never included —
# only variable NAMES travel (via extraLeads[].tokenEnvVar).
# Args: bridgePid distSha fromBranch mode campaignId leadLabel extraLeadsJson
qa_multilead_launch_manifest() {
	local bridge_pid="$1" dist_sha="$2" from_branch="$3" mode="$4"
	local campaign_id="$5" lead_label="$6" extra_leads_json="${7:-[]}"
	jq -n \
		--argjson bridgePid "$bridge_pid" \
		--arg distSha "$dist_sha" \
		--arg fromBranch "$from_branch" \
		--arg mode "$mode" \
		--arg cid "$campaign_id" \
		--arg leadLabel "$lead_label" \
		--argjson extraLeads "$extra_leads_json" \
		'{
      campaignId: $cid,
      bridgePid: $bridgePid,
      distSha: $distSha,
      fromBranch: $fromBranch,
      mode: $mode,
      leadLabel: $leadLabel,
      extraLeads: ($extraLeads | map({slotId, agentId, deptLabel, chatChannel, tokenEnvVar}))
    }'
}
