#!/usr/bin/env bash
# FLY-1189 H1: hermetic tests for the multi-Lead additive extension of
# scripts/test-deploy.sh / scripts/test-teardown.sh (lib: scripts/lib/qa-multilead.sh).
#
#   A1  FLYWHEEL_PROJECTS builder byte-compat (slotRole=lead, no new flags)
#   A2  FLYWHEEL_PROJECTS builder byte-compat (slotRole=cos → generalChannel)
#   A3  canonical config.yaml byte-compat
#   B1  --extra-lead → leads[] has exactly 2 entries, field-by-field
#   B2  --lead-label narrows main lead labels
#   C1  invalid --extra-lead specs rejected
#   C2  slot with missing/null fields rejected
#   C4  campaign args: dup slot / spec==main / non-slot mode / no main slot → rejected
#   D1  claim-set: second slot already locked → zero side effects (main lock rolled back)
#   D2  claim-set success → all locks claimed, sorted output
#   E1  claim-set partial failure (3rd of 3 held) → first two rolled back
#   H1  borrowed lock with LIVE campaign Bridge PID + old mtime → claim refuses
#   H2  borrowed lock with DEAD pid → claim refuses WITHOUT invoking stale teardown
#   F1  finalize writes same Bridge PID + sidecar into every lock; is_borrowed semantics
#   F2  manifest-driven extra-Lead teardown removes pid/session/manifest/workspace + kills supervisor
#   F3  release_borrowed_locks removes exactly the borrowed locks
#   W1  test-teardown.sh refuses a borrowed slot (fail-loud, lock intact)
#   W2  test-teardown.sh owner slot consumes campaign manifest (extra-lead residue gone)
#   L1  launch manifest records dist SHA, no token VALUES
#   S1  test-deploy.sh wiring sentinels (lib sourced, builders single-sourced, flags parsed)
set -uo pipefail

# The managed test sandbox denies process-table reads. Production leaves this
# unset and the teardown lease binds to the kernel-reported start time.
export FLYWHEEL_CMUX_PROCESS_INCARNATION_OVERRIDE="multilead-test-incarnation"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB="${SCRIPT_DIR}/lib/qa-multilead.sh"

PASSED=0
FAILED=0
pass() { PASSED=$((PASSED + 1)); echo "[TEST] ✓ $1"; }
fail() { FAILED=$((FAILED + 1)); echo "[TEST] ✗ $1"; }

if [[ ! -f "$LIB" ]]; then
  echo "FATAL: ${LIB} missing — implement scripts/lib/qa-multilead.sh first" >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$LIB"
for fn in qa_multilead_build_projects qa_multilead_config_yaml \
  qa_multilead_parse_spec qa_multilead_slot_fields \
  qa_multilead_validate_campaign_args qa_multilead_claim_one qa_multilead_claim_set \
  qa_multilead_finalize_locks qa_multilead_lock_is_borrowed \
  qa_multilead_teardown_extra_leads qa_multilead_release_borrowed_locks \
  qa_multilead_launch_manifest; do
  if ! type "$fn" >/dev/null 2>&1; then
    echo "FATAL: ${fn} not defined in ${LIB}" >&2
    exit 1
  fi
done

TMP="$(mktemp -d "${TMPDIR:-/tmp}/qa1189ml.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
export FLYWHEEL_CMUX_WATCHER_LOCK_DIR="${TMP}/cmux-watcher.lock"

# ── Fixture: slots file (schema mirrors ~/.flywheel/test-slots.json) ──
SLOTS="${TMP}/test-slots.json"
cat >"$SLOTS" <<'JSON'
{
  "guildId": "g-1",
  "slots": [
    {"id":1,"bridgePort":19871,"botName":"flywheel-test-1","tokenEnvVar":"TEST_BOT_TOKEN_1","botAppId":"111","channelId":"chan-1","role":"cos"},
    {"id":2,"bridgePort":19872,"botName":"flywheel-test-2","tokenEnvVar":"TEST_BOT_TOKEN_2","botAppId":"222","channelId":"chan-2","role":"lead","identitySource":"product-lead"},
    {"id":3,"bridgePort":19873,"botName":"flywheel-test-3","tokenEnvVar":"TEST_BOT_TOKEN_3","botAppId":"333","channelId":"chan-3","role":"lead","identitySource":"ops-lead"},
    {"id":4,"bridgePort":19874,"botName":"flywheel-test-4","tokenEnvVar":"TEST_BOT_TOKEN_4","botAppId":"","channelId":"chan-4","role":"lead"}
  ]
}
JSON

# ── Reference implementations for the canonical QA registry/config baseline.
# If the closed registry contract legitimately changes, update these fixtures
# in the same PR. ──
reference_build_projects() {
  jq -n \
    --arg projectName "$1" \
    --arg projectRoot "$2" \
    --arg projectRepo "$3" \
    --arg agentId "$4" \
    --arg chatChannel "$5" \
    --arg botTokenEnv "$6" \
    --arg slotRole "$7" \
    '
  [
    ({
      projectName: $projectName,
      projectRoot: $projectRoot,
      projectRepo: $projectRepo,
      leads: [
        {
          agentId: $agentId,
          summaryRole: "exempt",
          chatChannel: $chatChannel,
          botTokenEnv: $botTokenEnv,
          match: { labels: ["*"] }
        }
      ]
    })
    | if $slotRole == "cos" then . + { generalChannel: $chatChannel } else . end
  ]
  '
}

reference_config_yaml() {
  local TEST_PROJECT_NAME="$1"
  cat <<EOF
# Generated by scripts/test-deploy.sh (FLY-115 v1.24.3) — sandbox test config.
# DO NOT commit to xrliAnnie/flywheel-qa-sandbox; teardown wipes HOST_REPO.
project: ${TEST_PROJECT_NAME}

linear:
  team_id: FLY

runners:
  default: claude
  available:
    claude:
      type: claude
      model: sonnet

teams:
  - name: default
    orchestrators:
      - type: dag
        runner: claude

decision_layer:
  autonomy_level: advisor
  escalation_channel: discord

checkpoints:
  approve_to_ship:
    enabled: true
    timeout_ms: 14400000     # 4h (FLY-159: ConfigLoader floor; anything lower is warn+raised)
    timeout_behavior: fail-close
EOF
}

# ── A1/A2: canonical builder baseline ──
for role in lead cos; do
  ref="$(reference_build_projects test-slot-2 /tmp/hr xrliAnnie/flywheel-qa-sandbox flywheel-test-2 chan-2 TEST_BOT_TOKEN_2 "$role")"
  new="$(qa_multilead_build_projects test-slot-2 /tmp/hr xrliAnnie/flywheel-qa-sandbox flywheel-test-2 chan-2 TEST_BOT_TOKEN_2 "$role" '["*"]' '[]')"
  if [[ "$ref" == "$new" ]]; then
    pass "A-${role}: builder matches the canonical no-extra-lead baseline"
  else
    fail "A-${role}: builder output drifted from reference"
    diff <(printf '%s' "$ref") <(printf '%s' "$new") | head -10
  fi
done

# ── A3: config.yaml byte-compat ──
ref="$(reference_config_yaml test-slot-2)"
new="$(qa_multilead_config_yaml test-slot-2)"
if [[ "$ref" == "$new" ]]; then
  pass "A3: config.yaml byte-compat (no grace → byte-identical)"
else
  fail "A3: config.yaml drifted from reference"
  diff <(printf '%s' "$ref") <(printf '%s' "$new") | head -10
fi

# ── B1: two leads, field-by-field ──
EXTRAS='[{"slotId":3,"agentId":"flywheel-test-3","botAppId":"333","tokenEnvVar":"TEST_BOT_TOKEN_3","chatChannel":"chan-3","role":"lead","identitySource":"ops-lead","deptLabel":"Ops-Test","labels":["Ops-Test"]}]'
out="$(qa_multilead_build_projects test-slot-2 /tmp/hr repo flywheel-test-2 chan-2 TEST_BOT_TOKEN_2 lead '["Product-Test"]' "$EXTRAS")"
checks=(
  '.[0].leads | length == 2'
  '.[0].leads[0].agentId == "flywheel-test-2"'
  '.[0].leads[0].summaryRole == "exempt"'
  '.[0].leads[0].chatChannel == "chan-2"'
  '.[0].leads[0].botTokenEnv == "TEST_BOT_TOKEN_2"'
  '.[0].leads[0].match.labels == ["Product-Test"]'
  '.[0].leads[1].agentId == "flywheel-test-3"'
  '.[0].leads[1].summaryRole == "exempt"'
  '.[0].leads[1].chatChannel == "chan-3"'
  '.[0].leads[1].botTokenEnv == "TEST_BOT_TOKEN_3"'
  '.[0].leads[1].match.labels == ["Ops-Test"]'
  '.[0] | has("generalChannel") | not'
)
B1_OK=1
for c in "${checks[@]}"; do
  jq -e "$c" >/dev/null 2>&1 <<<"$out" || { B1_OK=0; fail "B1 check failed: $c"; }
done
[[ "$B1_OK" == "1" ]] && pass "B1: --extra-lead → exactly 2 leads, all fields correct"

# ── FLY-1726: the QA registry, not the manifest, owns Discord identity ──
IDENTITY_EXTRAS='[{"slotId":3,"agentId":"flywheel-test-3","botAppId":"33333333333333333","tokenEnvVar":"TEST_BOT_TOKEN_3","chatChannel":"chan-3","role":"lead","identitySource":"ops-lead","deptLabel":"Ops-Test","labels":["Ops-Test"],"discordStateDir":"/tmp/qa/extra-leads/slot-3/discord-state"}]'
identity_out="$(qa_multilead_build_projects test-slot-2 /tmp/hr repo flywheel-test-2 chan-2 TEST_BOT_TOKEN_2 lead '["Product-Test"]' "$IDENTITY_EXTRAS" "22222222222222222" "/tmp/qa/discord-state")"
if jq -e '
  .[0].leads[0].botUserId == "22222222222222222"
  and .[0].leads[0].discordStateDir == "/tmp/qa/discord-state"
  and .[0].leads[1].botUserId == "33333333333333333"
  and .[0].leads[1].discordStateDir == "/tmp/qa/extra-leads/slot-3/discord-state"
' >/dev/null 2>&1 <<<"$identity_out"; then
  pass "FLY-1726 B1: main and extra QA Leads carry canonical bot/state identity in registry"
else
  fail "FLY-1726 B1: QA registry omitted canonical botUserId/discordStateDir"
fi

# Compile the builder output through the production identity CLI. Shape-only
# checks missed the FLY-2030 closed-enum migration and let every 529 Lead fail
# before tmux startup.
IDENTITY_HOME="${TMP}/identity-home"
mkdir -p "${IDENTITY_HOME}/.flywheel"
printf '%s\n' '{"granularity":"per-lead","setBy":"test-deploy","setAt":"2026-08-28T00:00:00.000Z"}' \
  > "${IDENTITY_HOME}/.flywheel/summary-config.json"
IDENTITY_CLI="${SCRIPT_DIR}/../packages/flywheel-comm/dist/index.js"
IDENTITY_PROJECTS="${TMP}/identity-projects.json"
printf '%s\n' "$identity_out" > "$IDENTITY_PROJECTS"
IDENTITY_COMPILE_OK=1
for identity_lead in flywheel-test-2 flywheel-test-3; do
  if ! compiled_identity=$(node "$IDENTITY_CLI" lead-identity resolve \
      --projects-file "$IDENTITY_PROJECTS" \
      --project test-slot-2 --lead "$identity_lead" \
      --summary-config-home "$IDENTITY_HOME" --format json \
      2>"${TMP}/identity-${identity_lead}.err"); then
    IDENTITY_COMPILE_OK=0
    fail "FLY-2030 B1: canonical compiler rejected QA Lead ${identity_lead}"
    cat "${TMP}/identity-${identity_lead}.err"
    continue
  fi
  jq -e '
    .summaryRole == "exempt"
    and .hasSummaryDuty == false
    and .summaryGranularity == "per-lead"
    and (.summaryAssignmentDigest | test("^[a-f0-9]{64}$"))
  ' >/dev/null 2>&1 <<<"$compiled_identity" || {
    IDENTITY_COMPILE_OK=0
    fail "FLY-2030 B1: QA Lead ${identity_lead} compiled to a non-exempt summary identity"
  }
done
[[ "$IDENTITY_COMPILE_OK" == "1" ]] \
  && pass "FLY-2030 B1: real identity compiler accepts every QA Lead as summary-exempt"

# ── B2: --lead-label narrows main labels only ──
out="$(qa_multilead_build_projects test-slot-2 /tmp/hr repo flywheel-test-2 chan-2 TEST_BOT_TOKEN_2 lead '["Product-Test"]' '[]')"
if jq -e '.[0].leads[0].match.labels == ["Product-Test"] and (.[0].leads | length == 1)' >/dev/null 2>&1 <<<"$out"; then
  pass "B2: --lead-label narrows main lead labels"
else
  fail "B2: label narrowing broken"
fi

# ── C1: invalid specs ──
C1_OK=1
for bad in "abc:Ops-Test" "3" "0:X" "3:" ":Ops-Test" "3:has space" "-1:X"; do
  if qa_multilead_parse_spec "$bad" >/dev/null 2>&1; then
    C1_OK=0; fail "C1: spec '$bad' should be rejected"
  fi
done
if parsed="$(qa_multilead_parse_spec "3:Ops-Test" 2>/dev/null)" && [[ "$parsed" == "3 Ops-Test" ]]; then
  :
else
  C1_OK=0; fail "C1: valid spec '3:Ops-Test' should parse to '3 Ops-Test' (got '${parsed:-}')"
fi
[[ "$C1_OK" == "1" ]] && pass "C1: spec validation matrix"

# ── C2: slot with missing fields rejected; valid slot passes ──
C2_OK=1
if qa_multilead_slot_fields "$SLOTS" 4 >/dev/null 2>&1; then
  C2_OK=0; fail "C2: slot 4 (empty botAppId) should be rejected"
fi
if qa_multilead_slot_fields "$SLOTS" 9 >/dev/null 2>&1; then
  C2_OK=0; fail "C2: out-of-range slot 9 should be rejected"
fi
if f="$(qa_multilead_slot_fields "$SLOTS" 3 2>/dev/null)"; then
  jq -e '.agentId == "flywheel-test-3" and .tokenEnvVar == "TEST_BOT_TOKEN_3" and .chatChannel == "chan-3" and .botAppId == "333" and .role == "lead" and .identitySource == "ops-lead"' \
    >/dev/null 2>&1 <<<"$f" || { C2_OK=0; fail "C2: slot 3 fields wrong: $f"; }
else
  C2_OK=0; fail "C2: valid slot 3 should resolve"
fi
[[ "$C2_OK" == "1" ]] && pass "C2: slot fields validation"

# ── C4: campaign-args validation ──
C4_OK=1
# dup extra slot
if qa_multilead_validate_campaign_args "$SLOTS" slot 2 "3:Ops-Test" "3:Other" >/dev/null 2>&1; then
  C4_OK=0; fail "C4: duplicate extra slot should be rejected"
fi
# extra == main
if qa_multilead_validate_campaign_args "$SLOTS" slot 2 "2:Ops-Test" >/dev/null 2>&1; then
  C4_OK=0; fail "C4: extra slot == main slot should be rejected"
fi
# non-slot mode
if qa_multilead_validate_campaign_args "$SLOTS" mirror 2 "3:Ops-Test" >/dev/null 2>&1; then
  C4_OK=0; fail "C4: --extra-lead in mirror mode should be rejected"
fi
# missing main slot
if qa_multilead_validate_campaign_args "$SLOTS" slot "" "3:Ops-Test" >/dev/null 2>&1; then
  C4_OK=0; fail "C4: --extra-lead without explicit main slot should be rejected"
fi
# valid → JSON with slotId + deptLabel + resolved fields
if v="$(qa_multilead_validate_campaign_args "$SLOTS" slot 2 "3:Ops-Test" 2>/dev/null)"; then
  jq -e 'length == 1 and .[0].slotId == 3 and .[0].deptLabel == "Ops-Test" and .[0].agentId == "flywheel-test-3" and .[0].tokenEnvVar == "TEST_BOT_TOKEN_3" and .[0].chatChannel == "chan-3"' \
    >/dev/null 2>&1 <<<"$v" || { C4_OK=0; fail "C4: valid campaign args JSON wrong: $v"; }
else
  C4_OK=0; fail "C4: valid campaign args should pass"
fi
[[ "$C4_OK" == "1" ]] && pass "C4: campaign args validation matrix"

# ── Lock tests — all against a temp lock root ──
LOCK_ROOT="${TMP}/locks"
mkdir -p "$LOCK_ROOT"
STALE_PROBE="${TMP}/stale-invoked"
stale_probe() { echo "$1" >> "$STALE_PROBE"; }

# D2: claim-set success (run before D1 so the root starts clean)
rm -rf "${LOCK_ROOT:?}"/* "$STALE_PROBE"
if out="$(qa_multilead_claim_set "$LOCK_ROOT" stale_probe 3 2)"; then
  D2_OK=1
  [[ -d "${LOCK_ROOT}/flywheel-test-slot-2.lock" && -d "${LOCK_ROOT}/flywheel-test-slot-3.lock" ]] \
    || { D2_OK=0; fail "D2: both locks should exist"; }
  [[ "$(cat "${LOCK_ROOT}/flywheel-test-slot-2.lock/pid")" == "claiming" ]] \
    || { D2_OK=0; fail "D2: lock pid should be 'claiming'"; }
  # sorted order in output (2 before 3 even though passed 3 2)
  first="$(head -1 <<<"$out")"
  [[ "$first" == *"slot-2.lock" ]] || { D2_OK=0; fail "D2: claim order should be sorted (got first=$first)"; }
  [[ "$D2_OK" == "1" ]] && pass "D2: claim-set claims all slots sorted"
else
  fail "D2: claim-set on free slots should succeed"
fi

# D1: second slot already locked (live PID) → zero side effects
rm -rf "${LOCK_ROOT:?}"/* "$STALE_PROBE"
mkdir -p "${LOCK_ROOT}/flywheel-test-slot-3.lock"
echo "$$" > "${LOCK_ROOT}/flywheel-test-slot-3.lock/pid"
if qa_multilead_claim_set "$LOCK_ROOT" stale_probe 2 3 >/dev/null 2>&1; then
  fail "D1: claim-set should fail when slot 3 is held live"
else
  D1_OK=1
  [[ ! -d "${LOCK_ROOT}/flywheel-test-slot-2.lock" ]] || { D1_OK=0; fail "D1: slot-2 lock must be rolled back"; }
  [[ "$(cat "${LOCK_ROOT}/flywheel-test-slot-3.lock/pid")" == "$$" ]] || { D1_OK=0; fail "D1: slot-3 lock must be untouched"; }
  [[ ! -f "$STALE_PROBE" ]] || { D1_OK=0; fail "D1: stale teardown must NOT run for a live lock"; }
  [[ "$D1_OK" == "1" ]] && pass "D1: blocked claim-set → zero side effects"
fi

# E1: partial failure (3rd of 3 held) → first two rolled back
rm -rf "${LOCK_ROOT:?}"/* "$STALE_PROBE"
mkdir -p "${LOCK_ROOT}/flywheel-test-slot-4.lock"
echo "$$" > "${LOCK_ROOT}/flywheel-test-slot-4.lock/pid"
if qa_multilead_claim_set "$LOCK_ROOT" stale_probe 2 3 4 >/dev/null 2>&1; then
  fail "E1: claim-set should fail when slot 4 is held"
else
  E1_OK=1
  [[ ! -d "${LOCK_ROOT}/flywheel-test-slot-2.lock" ]] || { E1_OK=0; fail "E1: slot-2 must be rolled back"; }
  [[ ! -d "${LOCK_ROOT}/flywheel-test-slot-3.lock" ]] || { E1_OK=0; fail "E1: slot-3 must be rolled back"; }
  [[ -d "${LOCK_ROOT}/flywheel-test-slot-4.lock" ]] || { E1_OK=0; fail "E1: slot-4 (pre-held) must survive"; }
  [[ "$E1_OK" == "1" ]] && pass "E1: partial claim failure → full rollback"
fi

# F1: finalize + is_borrowed
rm -rf "${LOCK_ROOT:?}"/* "$STALE_PROBE"
qa_multilead_claim_set "$LOCK_ROOT" stale_probe 2 3 >/dev/null
if qa_multilead_finalize_locks "$LOCK_ROOT" "$$" 2 "camp-1" 2 3; then
  F1_OK=1
  [[ "$(cat "${LOCK_ROOT}/flywheel-test-slot-2.lock/pid")" == "$$" ]] || { F1_OK=0; fail "F1: owner lock pid must be Bridge PID"; }
  [[ "$(cat "${LOCK_ROOT}/flywheel-test-slot-3.lock/pid")" == "$$" ]] || { F1_OK=0; fail "F1: borrowed lock pid must be Bridge PID"; }
  if qa_multilead_lock_is_borrowed "${LOCK_ROOT}/flywheel-test-slot-2.lock" >/dev/null 2>&1; then
    F1_OK=0; fail "F1: owner lock must NOT read as borrowed"
  fi
  owner="$(qa_multilead_lock_is_borrowed "${LOCK_ROOT}/flywheel-test-slot-3.lock" 2>/dev/null)" \
    && [[ "$owner" == "2" ]] || { F1_OK=0; fail "F1: borrowed lock must point at owner slot 2 (got '${owner:-}')"; }
  [[ "$F1_OK" == "1" ]] && pass "F1: finalize writes Bridge PID + borrowed sidecar semantics"
else
  fail "F1: finalize_locks should succeed"
fi

# H1: borrowed lock, LIVE Bridge PID, mtime aged >300s → claim refuses, lock intact
touch -t 202601010000 "${LOCK_ROOT}/flywheel-test-slot-3.lock/pid" 2>/dev/null || true
if qa_multilead_claim_one "${LOCK_ROOT}/flywheel-test-slot-3.lock" stale_probe 3 >/dev/null 2>&1; then
  fail "H1: claim of a live-campaign borrowed lock must fail"
else
  H1_OK=1
  [[ "$(cat "${LOCK_ROOT}/flywheel-test-slot-3.lock/pid")" == "$$" ]] || { H1_OK=0; fail "H1: lock pid must be unchanged"; }
  [[ ! -f "$STALE_PROBE" ]] || { H1_OK=0; fail "H1: stale teardown must NOT run"; }
  [[ "$H1_OK" == "1" ]] && pass "H1: aged borrowed lock w/ live Bridge PID survives reclaim attempt"
fi

# H2: borrowed lock with DEAD pid → refuse AND never invoke stale teardown
rm -rf "${LOCK_ROOT:?}"/* "$STALE_PROBE"
mkdir -p "${LOCK_ROOT}/flywheel-test-slot-3.lock"
DEAD_PID=99999
while kill -0 "$DEAD_PID" 2>/dev/null; do DEAD_PID=$((DEAD_PID - 1)); done
echo "$DEAD_PID" > "${LOCK_ROOT}/flywheel-test-slot-3.lock/pid"
jq -n '{ownerSlot: 2, campaignId: "camp-x", borrowed: true}' > "${LOCK_ROOT}/flywheel-test-slot-3.lock/campaign.json"
if qa_multilead_claim_one "${LOCK_ROOT}/flywheel-test-slot-3.lock" stale_probe 3 >/dev/null 2>&1; then
  fail "H2: dead borrowed lock must not be silently reclaimed"
else
  H2_OK=1
  [[ ! -f "$STALE_PROBE" ]] || { H2_OK=0; fail "H2: stale teardown must NOT be invoked on a borrowed lock"; }
  [[ -d "${LOCK_ROOT}/flywheel-test-slot-3.lock" ]] || { H2_OK=0; fail "H2: borrowed lock must stay for owner teardown"; }
  [[ "$H2_OK" == "1" ]] && pass "H2: dead borrowed lock → fail-loud, no stale teardown"
fi

# ── F2: manifest-driven extra-Lead teardown ──
FAKEHOME="${TMP}/home"
mkdir -p "${FAKEHOME}/.flywheel/pids" "${FAKEHOME}/.flywheel/claude-sessions" \
  "${FAKEHOME}/.flywheel/manifests" "${FAKEHOME}/.flywheel/lead-workspace/flywheel-test-3"
# Orphaned spawn (NOT a child of this shell): a killed direct child stays a
# zombie until reaped, and `kill -0 <zombie>` still succeeds — which would
# false-fail the "supervisor killed" assertion. Reparenting to init makes the
# kill observable.
SUP_PID=$(bash -c 'sleep 300 >/dev/null 2>&1 & echo $!')
echo "$SUP_PID" > "${FAKEHOME}/.flywheel/pids/test-slot-2-flywheel-test-3.pid"
echo "sess-id" > "${FAKEHOME}/.flywheel/claude-sessions/test-slot-2-flywheel-test-3.session-id"
echo "{}" > "${FAKEHOME}/.flywheel/manifests/test-slot-2-flywheel-test-3.json"
echo "w" > "${FAKEHOME}/.flywheel/lead-workspace/flywheel-test-3/f.txt"
CAMPAIGN_MANIFEST="${TMP}/campaign-manifest.json"
jq -n \
  --arg pf "${FAKEHOME}/.flywheel/pids/test-slot-2-flywheel-test-3.pid" \
  --arg sf "${FAKEHOME}/.flywheel/claude-sessions/test-slot-2-flywheel-test-3.session-id" \
  --arg lm "${FAKEHOME}/.flywheel/manifests/test-slot-2-flywheel-test-3.json" \
  --arg lw "${FAKEHOME}/.flywheel/lead-workspace/flywheel-test-3" \
  '{
    campaignId: "camp-1", ownerSlot: 2, projectName: "test-slot-2",
    borrowedSlots: [3],
    extraLeads: [{
      slotId: 3, agentId: "flywheel-test-3", deptLabel: "Ops-Test",
      chatChannelId: "chan-3", botTokenEnv: "TEST_BOT_TOKEN_3",
      tmuxWindow: "test-slot-2-flywheel-test-3",
      pidFile: $pf, sessionIdFile: $sf, leadManifest: $lm, leadWorkspace: $lw
    }]
  }' > "$CAMPAIGN_MANIFEST"
qa_multilead_teardown_extra_leads "$CAMPAIGN_MANIFEST" >/dev/null 2>&1
F2_OK=1
sleep 0.3
kill -0 "$SUP_PID" 2>/dev/null && { F2_OK=0; fail "F2: supervisor pid should be killed"; kill -9 "$SUP_PID" 2>/dev/null; }
[[ ! -f "${FAKEHOME}/.flywheel/pids/test-slot-2-flywheel-test-3.pid" ]] || { F2_OK=0; fail "F2: pid file should be removed"; }
[[ ! -f "${FAKEHOME}/.flywheel/claude-sessions/test-slot-2-flywheel-test-3.session-id" ]] || { F2_OK=0; fail "F2: session-id should be removed"; }
[[ ! -f "${FAKEHOME}/.flywheel/manifests/test-slot-2-flywheel-test-3.json" ]] || { F2_OK=0; fail "F2: lead manifest should be removed"; }
[[ ! -d "${FAKEHOME}/.flywheel/lead-workspace/flywheel-test-3" ]] || { F2_OK=0; fail "F2: lead workspace should be removed"; }
[[ "$F2_OK" == "1" ]] && pass "F2: manifest-driven extra-Lead cleanup (pid/session/manifest/workspace)"

# ── F3: release_borrowed_locks removes exactly the borrowed locks ──
rm -rf "${LOCK_ROOT:?}"/*
mkdir -p "${LOCK_ROOT}/flywheel-test-slot-2.lock" "${LOCK_ROOT}/flywheel-test-slot-3.lock"
qa_multilead_release_borrowed_locks "$CAMPAIGN_MANIFEST" "$LOCK_ROOT"
F3_OK=1
[[ ! -d "${LOCK_ROOT}/flywheel-test-slot-3.lock" ]] || { F3_OK=0; fail "F3: borrowed slot-3 lock should be released"; }
[[ -d "${LOCK_ROOT}/flywheel-test-slot-2.lock" ]] || { F3_OK=0; fail "F3: owner slot-2 lock must NOT be touched"; }
[[ "$F3_OK" == "1" ]] && pass "F3: borrowed lock release is manifest-scoped"

# ── W1/W2: real test-teardown.sh wiring (tmux neutralized, HOME sandboxed) ──
STUB_BIN="${TMP}/stub-bin"
mkdir -p "$STUB_BIN"
cat > "${STUB_BIN}/tmux" <<'STUB'
#!/usr/bin/env bash
exit 1
STUB
chmod +x "${STUB_BIN}/tmux"

# W1: borrowed slot refusal (slot 27 — outside the real 4-slot pool)
W_LOCK="/tmp/flywheel-test-slot-27.lock"
rm -rf "$W_LOCK"
mkdir -p "$W_LOCK"
echo "claiming" > "${W_LOCK}/pid"
jq -n '{ownerSlot: 26, campaignId: "camp-w", borrowed: true}' > "${W_LOCK}/campaign.json"
if PATH="${STUB_BIN}:$PATH" HOME="$FAKEHOME" bash "${SCRIPT_DIR}/test-teardown.sh" 27 >/dev/null 2>&1; then
  fail "W1: teardown of a borrowed slot must fail loud"
  rm -rf "$W_LOCK"
else
  if [[ -d "$W_LOCK" && -f "${W_LOCK}/campaign.json" ]]; then
    pass "W1: borrowed-slot teardown refused, lock intact"
  else
    fail "W1: refusal must leave the borrowed lock untouched"
  fi
  rm -rf "$W_LOCK"
fi

# W2: owner slot teardown consumes the campaign manifest
W2_SLOT_DIR="/tmp/flywheel-test-slot-26"
W2_LOCK="/tmp/flywheel-test-slot-26.lock"
W2_BLOCK="/tmp/flywheel-test-slot-27.lock"
rm -rf "$W2_SLOT_DIR" "$W2_LOCK" "$W2_BLOCK"
mkdir -p "$W2_SLOT_DIR" "$W2_LOCK" "$W2_BLOCK"
echo "claiming" > "${W2_LOCK}/pid"
echo "claiming" > "${W2_BLOCK}/pid"
jq -n '{ownerSlot: 26, campaignId: "camp-w2", borrowed: true}' > "${W2_BLOCK}/campaign.json"
mkdir -p "${FAKEHOME}/.flywheel/pids" "${FAKEHOME}/.flywheel/claude-sessions" \
  "${FAKEHOME}/.flywheel/manifests" "${FAKEHOME}/.flywheel/lead-workspace/flywheel-test-27"
echo "99999" > "${FAKEHOME}/.flywheel/pids/test-slot-26-flywheel-test-27.pid"
echo "s" > "${FAKEHOME}/.flywheel/claude-sessions/test-slot-26-flywheel-test-27.session-id"
echo "{}" > "${FAKEHOME}/.flywheel/manifests/test-slot-26-flywheel-test-27.json"
jq -n \
  --arg pf "${FAKEHOME}/.flywheel/pids/test-slot-26-flywheel-test-27.pid" \
  --arg sf "${FAKEHOME}/.flywheel/claude-sessions/test-slot-26-flywheel-test-27.session-id" \
  --arg lm "${FAKEHOME}/.flywheel/manifests/test-slot-26-flywheel-test-27.json" \
  --arg lw "${FAKEHOME}/.flywheel/lead-workspace/flywheel-test-27" \
  '{
    campaignId: "camp-w2", ownerSlot: 26, projectName: "test-slot-26",
    borrowedSlots: [27],
    extraLeads: [{
      slotId: 27, agentId: "flywheel-test-27", deptLabel: "Ops-Test",
      chatChannelId: "c", botTokenEnv: "T",
      tmuxWindow: "test-slot-26-flywheel-test-27",
      pidFile: $pf, sessionIdFile: $sf, leadManifest: $lm, leadWorkspace: $lw
    }]
  }' > "${W2_SLOT_DIR}/campaign-manifest.json"
PATH="${STUB_BIN}:$PATH" HOME="$FAKEHOME" bash "${SCRIPT_DIR}/test-teardown.sh" 26 >/dev/null 2>&1
W2_OK=1
[[ ! -f "${FAKEHOME}/.flywheel/pids/test-slot-26-flywheel-test-27.pid" ]] || { W2_OK=0; fail "W2: extra-lead pid file should be removed"; }
[[ ! -f "${FAKEHOME}/.flywheel/claude-sessions/test-slot-26-flywheel-test-27.session-id" ]] || { W2_OK=0; fail "W2: extra-lead session-id should be removed"; }
[[ ! -d "${FAKEHOME}/.flywheel/lead-workspace/flywheel-test-27" ]] || { W2_OK=0; fail "W2: extra-lead workspace should be removed"; }
[[ ! -d "$W2_BLOCK" ]] || { W2_OK=0; fail "W2: borrowed slot-27 lock should be released by owner teardown"; }
[[ ! -d "$W2_LOCK" ]] || { W2_OK=0; fail "W2: owner lock should be released"; }
[[ ! -d "$W2_SLOT_DIR" ]] || { W2_OK=0; fail "W2: owner SLOT_DIR should be removed"; }
[[ "$W2_OK" == "1" ]] && pass "W2: owner teardown consumes campaign manifest (no extra-Lead residue)"
rm -rf "$W2_SLOT_DIR" "$W2_LOCK" "$W2_BLOCK"

# ── L1: launch manifest (SHA present; no token values) ──
FAKE_TOKEN_VALUE="supersecret-token-value-xyz"
export TEST_BOT_TOKEN_3="$FAKE_TOKEN_VALUE"
lm="$(qa_multilead_launch_manifest 12345 deadbeefsha main slot camp-1 "Product-Test" "$EXTRAS")"
L1_OK=1
jq -e '.bridgePid == 12345' >/dev/null 2>&1 <<<"$lm" || { L1_OK=0; fail "L1: bridgePid missing"; }
jq -e '.distSha == "deadbeefsha"' >/dev/null 2>&1 <<<"$lm" || { L1_OK=0; fail "L1: distSha missing"; }
jq -e '.extraLeads[0].agentId == "flywheel-test-3" and .extraLeads[0].deptLabel == "Ops-Test"' >/dev/null 2>&1 <<<"$lm" || { L1_OK=0; fail "L1: extraLeads missing"; }
if grep -q "$FAKE_TOKEN_VALUE" <<<"$lm"; then
  L1_OK=0; fail "L1: manifest must NOT contain token VALUES"
fi
unset TEST_BOT_TOKEN_3
[[ "$L1_OK" == "1" ]] && pass "L1: launch manifest records SHA without secrets"

# ── S1: test-deploy.sh wiring sentinels ──
S1_OK=1
DEPLOY="${SCRIPT_DIR}/test-deploy.sh"
bash -n "$DEPLOY" 2>/dev/null || { S1_OK=0; fail "S1: test-deploy.sh has syntax errors"; }
bash -n "${SCRIPT_DIR}/test-teardown.sh" 2>/dev/null || { S1_OK=0; fail "S1: test-teardown.sh has syntax errors"; }
grep -q 'qa-multilead.sh' "$DEPLOY" || { S1_OK=0; fail "S1: test-deploy.sh must source lib/qa-multilead.sh"; }
grep -q -- '--extra-lead' "$DEPLOY" || { S1_OK=0; fail "S1: --extra-lead flag not parsed"; }
grep -q -- '--lead-label' "$DEPLOY" || { S1_OK=0; fail "S1: --lead-label flag not parsed"; }
grep -q 'qa_multilead_build_projects' "$DEPLOY" || { S1_OK=0; fail "S1: FLYWHEEL_PROJECTS must be built via qa_multilead_build_projects"; }
grep -q 'qa_multilead_config_yaml' "$DEPLOY" || { S1_OK=0; fail "S1: config.yaml must be generated via qa_multilead_config_yaml"; }
grep -q 'QA_SUMMARY_CONFIG_HOME="${SLOT_DIR}/identity-home"' "$DEPLOY" \
  || { S1_OK=0; fail "FLY-2030 S1: QA summary config must live under the slot"; }
grep -q 'summary-config.json' "$DEPLOY" \
  || { S1_OK=0; fail "FLY-2030 S1: test-deploy must materialize summary config"; }
if grep -q -- '--arg projectName "$TEST_PROJECT_NAME" --arg botTokenEnv' "$DEPLOY"; then
  S1_OK=0; fail "FLY-1726 S1: QA v2 manifest still declares botTokenEnv"
fi
if grep -q '"FLYWHEEL_PROJECTS=$(jq -c' "$DEPLOY"; then
  S1_OK=0; fail "FLY-1726 S1: QA Lead launch environment still projects raw registry JSON"
fi
DEFAULT_LEAD_ENV_COUNT=$(grep -c 'TEAMLEAD_DEFAULT_LEAD_AGENT="${AGENT_ID}"' "$DEPLOY" || true)
[[ "$DEFAULT_LEAD_ENV_COUNT" -eq 3 ]] \
  || { S1_OK=0; fail "FLY-1726 S1: all three QA Bridge launch branches must carry TEAMLEAD_DEFAULT_LEAD_AGENT" "count=${DEFAULT_LEAD_ENV_COUNT}"; }
grep -q 'TEAMLEAD_DEFAULT_LEAD_AGENT requires non-empty AGENT_ID' "$DEPLOY" \
  || { S1_OK=0; fail "FLY-1726 S1: QA Bridge launch must fail loudly when AGENT_ID is empty"; }
# The old inline builder must be GONE (single source) — its distinctive line:
if grep -q 'match: { labels: \["\*"\] }' "$DEPLOY"; then
  S1_OK=0; fail "S1: old inline FLYWHEEL_PROJECTS builder still present (double source)"
fi
grep -q 'qa_multilead_lock_is_borrowed' "${SCRIPT_DIR}/test-teardown.sh" || { S1_OK=0; fail "S1: teardown must guard borrowed slots"; }
grep -q 'qa_multilead_teardown_extra_leads' "${SCRIPT_DIR}/test-teardown.sh" || { S1_OK=0; fail "S1: teardown must consume campaign manifest"; }
[[ "$S1_OK" == "1" ]] && pass "S1: deploy/teardown wiring sentinels"

echo "=================================="
echo "test-deploy-multilead tests: ${PASSED} passed, ${FAILED} failed"
[ "$FAILED" -eq 0 ]
