#!/bin/bash
# FLY-74: Lead daemon management CLI.
# Generates launchd plists from manifests, manages Lead lifecycle.
#
# Usage: flywheel-daemon.sh <command> [options]
#
# Commands:
#   install [lead-id|--all]   Generate plist + register with launchd
#   uninstall [lead-id|--all] Unregister from launchd + remove plist
#   restart [lead-id|--all]   Stop + start (launchctl kickstart -k)
#   status                    Show all Lead daemon statuses
#   logs [lead-id]            Tail Lead log file
#
# Lead identification uses {project}-{lead-id} from manifest filenames
# to avoid cross-project collisions (e.g., two projects both having
# a "product-lead"). The CLI accepts just lead-id for convenience
# when there's no ambiguity.
#
# Prerequisites:
#   - jq installed
#   - Manifests exist at ~/.flywheel/manifests/ (generated by claude-lead.sh)
#   - ~/.flywheel/.env contains bot tokens and config
#
# The wrapper script (flywheel-lead-wrapper.sh) is installed to ~/.flywheel/bin/
# automatically on first install.
set -euo pipefail

FLYWHEEL_DIR="${HOME}/Dev/flywheel"
MANIFEST_DIR="${HOME}/.flywheel/manifests"
PLIST_DIR="${HOME}/Library/LaunchAgents"
FLYWHEEL_BIN="${HOME}/.flywheel/bin"
PID_DIR="${HOME}/.flywheel/pids"
PLIST_PREFIX="com.flywheel.lead"
GUI_DOMAIN="gui/$(id -u)"

# ════════════════════════════════════════════════════════════════
# Utility functions
# ════════════════════════════════════════════════════════════════

log() {
  echo "[daemon] $*"
}

error() {
  echo "[daemon] ERROR: $*" >&2
  exit 1
}

require_jq() {
  command -v jq >/dev/null 2>&1 || error "jq is required but not found. Install: brew install jq"
}

# Derive a daemon key from manifest filename.
# Manifest: {project}-{lead-id}.json → daemon key: {project}-{lead-id}
# This preserves the project scope that existing Lead infra uses.
daemon_key_from_manifest() {
  local manifest="$1"
  basename "$manifest" .json
}

# Get plist label from daemon key
plist_label() {
  echo "${PLIST_PREFIX}.${1}"
}

# Get plist file path from daemon key
plist_path() {
  echo "${PLIST_DIR}/$(plist_label "$1").plist"
}

# Get log file path from daemon key
log_path() {
  local daemon_key="$1"
  echo "/tmp/flywheel-lead-${daemon_key}.log"
}

# Find manifest file(s) matching a lead-id or daemon-key.
# Returns manifest path(s), one per line.
# Exits 1 if no match found.
find_manifests() {
  local query="$1"
  local found=0

  # Try exact daemon-key match first: {query}.json
  if [ -f "${MANIFEST_DIR}/${query}.json" ]; then
    echo "${MANIFEST_DIR}/${query}.json"
    return 0
  fi

  # Try lead-id suffix match: *-{query}.json
  for f in "${MANIFEST_DIR}"/*-"${query}.json"; do
    if [ -f "$f" ]; then
      echo "$f"
      found=$((found + 1))
    fi
  done

  [ "$found" -gt 0 ] && return 0
  return 1
}

# List all manifest files
list_manifests() {
  for f in "${MANIFEST_DIR}"/*.json; do
    [ -f "$f" ] && echo "$f"
  done
}

# Check if a launchd service is loaded
is_loaded() {
  local daemon_key="$1"
  launchctl print "${GUI_DOMAIN}/$(plist_label "$daemon_key")" &>/dev/null
}

# Get PID of a running launchd service (0 if not running)
get_launchd_pid() {
  local daemon_key="$1"
  local label
  label=$(plist_label "$daemon_key")
  local pid
  pid=$(launchctl print "${GUI_DOMAIN}/${label}" 2>/dev/null | grep -m1 'pid =' | awk '{print $NF}' || true)
  echo "${pid:-0}"
}

# ════════════════════════════════════════════════════════════════
# Install wrapper script
# ════════════════════════════════════════════════════════════════

install_wrapper() {
  local src="${FLYWHEEL_DIR}/scripts/flywheel-lead-wrapper.sh"
  local dst="${FLYWHEEL_BIN}/flywheel-lead-wrapper.sh"

  if [ ! -f "$src" ]; then
    error "Wrapper source not found: ${src}"
  fi

  mkdir -p "$FLYWHEEL_BIN"
  cp "$src" "$dst"
  chmod +x "$dst"
  log "Wrapper installed: ${dst}"
}

# ════════════════════════════════════════════════════════════════
# Generate launchd plist
# ════════════════════════════════════════════════════════════════

generate_plist() {
  local daemon_key="$1"
  local manifest_path="$2"
  local plist
  plist=$(plist_path "$daemon_key")
  local label
  label=$(plist_label "$daemon_key")
  local wrapper="${FLYWHEEL_BIN}/flywheel-lead-wrapper.sh"
  local logfile
  logfile=$(log_path "$daemon_key")

  mkdir -p "$PLIST_DIR"

  cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>${label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${wrapper}</string>
        <string>${manifest_path}</string>
    </array>
    <key>KeepAlive</key><true/>
    <key>ThrottleInterval</key><integer>30</integer>
    <key>RunAtLoad</key><true/>
    <key>StandardOutPath</key><string>${logfile}</string>
    <key>StandardErrorPath</key><string>${logfile}</string>
</dict>
</plist>
EOF

  log "Plist generated: ${plist}"
}

# ════════════════════════════════════════════════════════════════
# Commands
# ════════════════════════════════════════════════════════════════

cmd_install() {
  local target="${1:---all}"
  require_jq

  # Install wrapper (shared by all leads)
  install_wrapper

  if [ "$target" = "--all" ]; then
    local count=0
    for manifest in $(list_manifests); do
      install_one_manifest "$manifest"
      count=$((count + 1))
    done
    if [ "$count" -eq 0 ]; then
      log "No manifests found in ${MANIFEST_DIR}/. Run claude-lead.sh first."
    else
      log "Installed ${count} Lead daemon(s)."
    fi
  else
    local manifests
    manifests=$(find_manifests "$target") || error "No manifest for '${target}' in ${MANIFEST_DIR}/"
    local count=0
    while IFS= read -r manifest; do
      install_one_manifest "$manifest"
      count=$((count + 1))
    done <<< "$manifests"
    if [ "$count" -gt 1 ]; then
      log "Installed ${count} Leads matching '${target}'."
    fi
  fi
}

install_one_manifest() {
  local manifest="$1"
  local daemon_key
  daemon_key=$(daemon_key_from_manifest "$manifest")
  local lead_id
  lead_id=$(jq -r '.leadId' "$manifest")

  # Validate manifest
  local project_dir
  project_dir=$(jq -r '.projectDir' "$manifest")
  if [ -z "$project_dir" ] || [ "$project_dir" = "null" ]; then
    error "Manifest missing projectDir: ${manifest}"
  fi

  local label
  label=$(plist_label "$daemon_key")

  # Unload existing if loaded (idempotent reinstall)
  if is_loaded "$daemon_key"; then
    log "Unloading existing ${label}..."
    launchctl bootout "${GUI_DOMAIN}/${label}" 2>/dev/null || true
    sleep 1
  fi

  generate_plist "$daemon_key" "$manifest"

  local plist
  plist=$(plist_path "$daemon_key")
  launchctl bootstrap "$GUI_DOMAIN" "$plist"
  log "Registered: ${label}"

  # Verify
  sleep 2
  if is_loaded "$daemon_key"; then
    local pid
    pid=$(get_launchd_pid "$daemon_key")
    log "Lead '${lead_id}' (${daemon_key}) daemon installed and running (PID: ${pid})."
  else
    log "WARNING: ${label} registered but not yet running. Check: launchctl print ${GUI_DOMAIN}/${label}"
  fi
}

cmd_uninstall() {
  local target="${1:---all}"

  if [ "$target" = "--all" ]; then
    local count=0
    # Uninstall all known manifests
    for manifest in $(list_manifests); do
      local daemon_key
      daemon_key=$(daemon_key_from_manifest "$manifest")
      uninstall_one "$daemon_key"
      count=$((count + 1))
    done
    # Also check for orphaned plists (no manifest but plist exists)
    for plist in "${PLIST_DIR}/${PLIST_PREFIX}".*.plist; do
      [ -f "$plist" ] || continue
      local label
      label=$(basename "$plist" .plist)
      local daemon_key="${label#${PLIST_PREFIX}.}"
      if [ ! -f "${MANIFEST_DIR}/${daemon_key}.json" ]; then
        log "Removing orphaned plist: ${plist}"
        launchctl bootout "${GUI_DOMAIN}/${label}" 2>/dev/null || true
        rm -f "$plist"
        count=$((count + 1))
      fi
    done
    log "Uninstalled ${count} Lead daemon(s)."
  else
    local manifests
    manifests=$(find_manifests "$target") || error "No manifest for '${target}' in ${MANIFEST_DIR}/"
    while IFS= read -r manifest; do
      local daemon_key
      daemon_key=$(daemon_key_from_manifest "$manifest")
      uninstall_one "$daemon_key"
    done <<< "$manifests"
  fi
}

uninstall_one() {
  local daemon_key="$1"
  local label
  label=$(plist_label "$daemon_key")
  local plist
  plist=$(plist_path "$daemon_key")

  if is_loaded "$daemon_key"; then
    launchctl bootout "${GUI_DOMAIN}/${label}" 2>/dev/null || true
    log "Unloaded: ${label}"
  fi

  if [ -f "$plist" ]; then
    rm -f "$plist"
    log "Removed: ${plist}"
  fi

  log "Daemon '${daemon_key}' uninstalled."
}

cmd_restart() {
  local target="${1:---all}"

  if [ "$target" = "--all" ]; then
    for manifest in $(list_manifests); do
      local daemon_key
      daemon_key=$(daemon_key_from_manifest "$manifest")
      restart_one "$daemon_key"
    done
  else
    local manifests
    manifests=$(find_manifests "$target") || error "No manifest for '${target}' in ${MANIFEST_DIR}/"
    while IFS= read -r manifest; do
      local daemon_key
      daemon_key=$(daemon_key_from_manifest "$manifest")
      restart_one "$daemon_key"
    done <<< "$manifests"
  fi
}

restart_one() {
  local daemon_key="$1"
  local label
  label=$(plist_label "$daemon_key")

  if ! is_loaded "$daemon_key"; then
    log "Daemon '${daemon_key}' is not loaded. Use 'install' first."
    return 1
  fi

  log "Restarting ${daemon_key}..."
  launchctl kickstart -k "${GUI_DOMAIN}/${label}"
  sleep 2
  local pid
  pid=$(get_launchd_pid "$daemon_key")
  log "Daemon '${daemon_key}' restarted (PID: ${pid})."
}

cmd_status() {
  require_jq

  local has_leads=false

  printf "\n%-18s  %-14s  %-18s  %-8s  %s\n" "DAEMON KEY" "LEAD" "LAUNCHD" "PID" "LOG"
  printf "%-18s  %-14s  %-18s  %-8s  %s\n" "──────────" "────" "───────" "───" "───"

  # Check all manifests
  for f in "${MANIFEST_DIR}"/*.json; do
    [ -f "$f" ] || continue
    has_leads=true
    local daemon_key
    daemon_key=$(daemon_key_from_manifest "$f")
    local lead_id
    lead_id=$(jq -r '.leadId' "$f")

    local state="not installed"
    local pid="--"
    local logfile
    logfile=$(log_path "$daemon_key")

    if [ -f "$(plist_path "$daemon_key")" ]; then
      if is_loaded "$daemon_key"; then
        pid=$(get_launchd_pid "$daemon_key")
        if [ "$pid" != "0" ] && [ -n "$pid" ]; then
          state="running"
        else
          state="loaded (idle)"
          pid="--"
        fi
      else
        state="installed (unloaded)"
      fi
    fi

    local log_info="--"
    if [ -f "$logfile" ]; then
      local size
      size=$(wc -c < "$logfile" | tr -d ' ')
      local human_size
      if (( size > 1048576 )); then
        human_size="$((size / 1048576))M"
      elif (( size > 1024 )); then
        human_size="$((size / 1024))K"
      else
        human_size="${size}B"
      fi
      log_info="${logfile} (${human_size})"
    fi

    printf "%-18s  %-14s  %-18s  %-8s  %s\n" "$daemon_key" "$lead_id" "$state" "$pid" "$log_info"
  done

  if [ "$has_leads" = false ]; then
    log "No manifests found. Run claude-lead.sh first to generate manifests."
  fi

  echo ""

  # Also show other flywheel launchd services
  printf "Other Flywheel services:\n"
  for label in com.flywheel.daily-standup com.flywheel.updater; do
    local svc_state="not loaded"
    if launchctl print "${GUI_DOMAIN}/${label}" &>/dev/null; then
      svc_state="loaded"
    fi
    printf "  %-32s  %s\n" "$label" "$svc_state"
  done
  echo ""
}

cmd_logs() {
  local target="${1:-}"
  if [ -z "$target" ]; then
    error "Usage: flywheel-daemon.sh logs <lead-id>"
  fi

  require_jq

  # Resolve to daemon key
  local manifests
  manifests=$(find_manifests "$target") || error "No manifest for '${target}'"
  local manifest
  manifest=$(echo "$manifests" | head -1)
  local daemon_key
  daemon_key=$(daemon_key_from_manifest "$manifest")

  local logfile
  logfile=$(log_path "$daemon_key")
  if [ ! -f "$logfile" ]; then
    error "Log file not found: ${logfile}"
  fi

  log "Tailing ${logfile} (Ctrl+C to stop)..."
  tail -f "$logfile"
}

# ════════════════════════════════════════════════════════════════
# Main
# ════════════════════════════════════════════════════════════════

usage() {
  cat <<'EOF'
Usage: flywheel-daemon.sh <command> [options]

Commands:
  install [lead-id|--all]   Generate plist + register with launchd
  uninstall [lead-id|--all] Unregister from launchd + remove plist
  restart [lead-id|--all]   Restart Lead daemon (kickstart -k)
  status                    Show all Lead daemon statuses
  logs <lead-id>            Tail Lead log file

Identification:
  lead-id can be just the Lead name (e.g., "product-lead") or the
  full daemon key "project-lead-id" (e.g., "geoforge3d-product-lead").
  Use the full key when multiple projects have the same Lead name.

Examples:
  flywheel-daemon.sh install --all
  flywheel-daemon.sh install product-lead
  flywheel-daemon.sh status
  flywheel-daemon.sh restart cos-lead
  flywheel-daemon.sh logs product-lead
  flywheel-daemon.sh uninstall --all
EOF
}

COMMAND="${1:-}"
shift || true

case "$COMMAND" in
  install)   cmd_install "$@" ;;
  uninstall) cmd_uninstall "$@" ;;
  restart)   cmd_restart "$@" ;;
  status)    cmd_status ;;
  logs)      cmd_logs "$@" ;;
  -h|--help|help) usage ;;
  "")        usage; exit 1 ;;
  *)         error "Unknown command: ${COMMAND}. Run with --help for usage." ;;
esac
