#!/usr/bin/env bash
# FLY-1887 + FLY-2003: atomically vendor the one-shot guard and truthful Codex
# profile stack, then converge independent global shims. DISABLED applies only
# to the one-shot guard; identity status/manual selection always stays managed.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNNER_DIR="$SCRIPT_DIR/../packages/claude-runner"
SOURCE_WRAPPER="$SCRIPT_DIR/codex-with-fallback.sh"
SOURCE_GUARD="$SCRIPT_DIR/lib/codex-guard.sh"
SOURCE_PROFILE="$RUNNER_DIR/bin/flywheel-codex-profile.mjs"
SOURCE_CORE="$RUNNER_DIR/bin/codex-account-core.mjs"
SOURCE_CORE_TYPES="$RUNNER_DIR/bin/codex-account-core.d.mts"
SOURCE_REGISTRY="$RUNNER_DIR/agents/codex-account-registry.json"

GLOBAL_BIN_DIR="${FLYWHEEL_CODEX_GLOBAL_BIN_DIR:-$HOME/.local/bin}"
LIBEXEC_DIR="${FLYWHEEL_CODEX_GUARD_INSTALL_ROOT:-$HOME/.flywheel/libexec/codex-guard}"
RELEASES_DIR="$LIBEXEC_DIR/releases"
CURRENT_LINK="$LIBEXEC_DIR/current"
GLOBAL_SHIM="$GLOBAL_BIN_DIR/codex-with-fallback"
GLOBAL_PROFILE_SHIM="$GLOBAL_BIN_DIR/codex-profile"
BACKUP="$GLOBAL_SHIM.bak"
PROFILE_BACKUP="$GLOBAL_PROFILE_SHIM.bak"
DISABLE_SENTINEL="$LIBEXEC_DIR/DISABLED"
MANAGED_SHIM_SENTINEL="# FLYWHEEL_CODEX_GUARD_MANAGED_SHIM=1"
MANAGED_PROFILE_SENTINEL="# FLYWHEEL_CODEX_PROFILE_MANAGED_SHIM=1"

die() { printf '[install-codex-guard] ERROR: %s\n' "$*" >&2; exit 1; }

shim_file_is_managed() {
  local candidate="$1"
  [[ -f "$candidate" && ! -L "$candidate" ]] || return 1
  grep -Fxq "$MANAGED_SHIM_SENTINEL" "$candidate" 2>/dev/null && return 0
  # Recognize the unmarked shim emitted by the pre-sentinel guard installer.
  grep -Fq '[codex-guard] INSTALL_ERROR stable wrapper is missing' "$candidate" 2>/dev/null \
    && grep -Fq 'exec "$target" "$@"' "$candidate" 2>/dev/null
}

profile_shim_file_is_managed() {
  local candidate="$1"
  [[ -f "$candidate" && ! -L "$candidate" ]] || return 1
  grep -Fxq "$MANAGED_PROFILE_SENTINEL" "$candidate" 2>/dev/null && return 0
  # Recognize an unmarked early FLY-2003 shim so a rerun never backs up its own
  # generated bytes as the user's once-only legacy rollback.
  grep -Fq '[codex-profile] INSTALL_ERROR stable profile CLI is missing' "$candidate" 2>/dev/null \
    && grep -Fq 'flywheel-codex-profile.mjs' "$candidate" 2>/dev/null
}

publish_current_symlink() {
  local staged="$1" target="$2"
  [[ ! -e "$target" || -L "$target" ]] \
    || die "current target is not a symlink: $target"
  /bin/mv -fT "$staged" "$target" 2>/dev/null && return 0
  /bin/mv -fh "$staged" "$target" 2>/dev/null && return 0
  return 1
}

node_bin="${FLYWHEEL_NODE_BIN:-node}"
if [[ "$node_bin" == */* ]]; then
  [[ -x "$node_bin" ]] || die "Node executable is not executable: $node_bin"
elif ! command -v "$node_bin" >/dev/null 2>&1; then
  die "Node executable was not found: $node_bin"
fi

for source_file in \
  "$SOURCE_WRAPPER" "$SOURCE_GUARD" "$SOURCE_PROFILE" \
  "$SOURCE_CORE" "$SOURCE_CORE_TYPES" "$SOURCE_REGISTRY"; do
  [[ -f "$source_file" && ! -L "$source_file" ]] \
    || die "repo release source is missing or unsafe: $source_file"
done
/bin/bash -n "$SOURCE_WRAPPER" || die "wrapper source failed bash -n"
/bin/bash -n "$SOURCE_GUARD" || die "guard source failed bash -n"
"$node_bin" --check "$SOURCE_PROFILE" >/dev/null \
  || die "profile source failed node --check"
"$node_bin" --check "$SOURCE_CORE" >/dev/null \
  || die "account core source failed node --check"

content_hash="$({
  shasum -a 256 "$SOURCE_WRAPPER"
  shasum -a 256 "$SOURCE_GUARD"
  shasum -a 256 "$SOURCE_PROFILE"
  shasum -a 256 "$SOURCE_CORE"
  shasum -a 256 "$SOURCE_CORE_TYPES"
  shasum -a 256 "$SOURCE_REGISTRY"
} | shasum -a 256 | awk '{print $1}')"
case "$content_hash" in ''|*[!0-9a-f]*) die "could not derive content hash" ;; esac

mkdir -p "$RELEASES_DIR" "$GLOBAL_BIN_DIR" || die "cannot create install directories"
chmod 700 "$LIBEXEC_DIR" "$RELEASES_DIR" 2>/dev/null || true
release_dir="$RELEASES_DIR/$content_hash"
if [[ ! -d "$release_dir" ]]; then
  stage="$RELEASES_DIR/.stage-$content_hash-$$"
  [[ ! -e "$stage" ]] || die "staging path already exists: $stage"
  mkdir "$stage" || die "cannot create release stage"
  if ! cp "$SOURCE_WRAPPER" "$stage/codex-with-fallback.sh" \
    || ! cp "$SOURCE_GUARD" "$stage/codex-guard.sh" \
    || ! cp "$SOURCE_PROFILE" "$stage/flywheel-codex-profile.mjs" \
    || ! cp "$SOURCE_CORE" "$stage/codex-account-core.mjs" \
    || ! cp "$SOURCE_CORE_TYPES" "$stage/codex-account-core.d.mts" \
    || ! cp "$SOURCE_REGISTRY" "$stage/codex-account-registry.json"; then
    rm -rf "$stage" 2>/dev/null || true
    die "cannot stage release"
  fi
  chmod 555 "$stage/codex-with-fallback.sh" "$stage/codex-guard.sh" \
    "$stage/flywheel-codex-profile.mjs" \
    || { rm -rf "$stage" 2>/dev/null || true; die "cannot lock executable release modes"; }
  chmod 444 "$stage/codex-account-core.mjs" \
    "$stage/codex-account-core.d.mts" "$stage/codex-account-registry.json" \
    || { rm -rf "$stage" 2>/dev/null || true; die "cannot lock data release modes"; }
  /bin/bash -n "$stage/codex-with-fallback.sh" \
    && /bin/bash -n "$stage/codex-guard.sh" \
    && "$node_bin" --check "$stage/flywheel-codex-profile.mjs" >/dev/null \
    && "$node_bin" --check "$stage/codex-account-core.mjs" >/dev/null \
    || { rm -rf "$stage" 2>/dev/null || true; die "staged release failed self-check"; }
  mv "$stage" "$release_dir" || die "cannot publish release"
fi

link_tmp="$LIBEXEC_DIR/.current-$$"
rm -f "$link_tmp" 2>/dev/null || true
ln -s "releases/$content_hash" "$link_tmp" || die "cannot stage current symlink"
publish_current_symlink "$link_tmp" "$CURRENT_LINK" \
  || { rm -f "$link_tmp" 2>/dev/null || true; die "cannot publish current symlink"; }

# Preserve each pre-managed global command exactly once, independently.
if [[ ! -e "$BACKUP" && ! -L "$BACKUP" \
  && ( -e "$GLOBAL_SHIM" || -L "$GLOBAL_SHIM" ) ]] \
  && ! shim_file_is_managed "$GLOBAL_SHIM"; then
  cp -p "$GLOBAL_SHIM" "$BACKUP" || die "cannot preserve original wrapper backup"
fi
if [[ ! -e "$PROFILE_BACKUP" && ! -L "$PROFILE_BACKUP" \
  && ( -e "$GLOBAL_PROFILE_SHIM" || -L "$GLOBAL_PROFILE_SHIM" ) ]] \
  && ! profile_shim_file_is_managed "$GLOBAL_PROFILE_SHIM"; then
  cp -p "$GLOBAL_PROFILE_SHIM" "$PROFILE_BACKUP" \
    || die "cannot preserve original profile backup"
fi

# Profile convergence is unconditional: DISABLED is a guard rollback only.
profile_tmp="$GLOBAL_BIN_DIR/.codex-profile.tmp.$$"
{
  printf '#!/usr/bin/env bash\n'
  printf '%s\n' "$MANAGED_PROFILE_SENTINEL"
  printf 'set -uo pipefail\n'
  printf 'NODE_BIN="${FLYWHEEL_NODE_BIN:-node}"\n'
  printf 'target=%q\n' "$CURRENT_LINK/flywheel-codex-profile.mjs"
  printf 'registry=%q\n' "$CURRENT_LINK/codex-account-registry.json"
  printf 'global_home=%q\n' "$HOME/.codex"
  printf 'global_profiles=%q\n' "$HOME/.codex/profiles"
  printf 'global_ledger=%q\n' "$HOME/.flywheel/codex-account-ledger"
  printf '%s\n' 'if [[ "$NODE_BIN" == */* ]]; then'
  printf '%s\n' '  [[ -x "$NODE_BIN" ]] || { printf '\''[codex-profile] INSTALL_ERROR Node executable is unavailable\n'\'' >&2; exit 125; }'
  printf '%s\n' 'elif ! command -v "$NODE_BIN" >/dev/null 2>&1; then'
  printf '%s\n' '  printf '\''[codex-profile] INSTALL_ERROR Node executable is unavailable\n'\'' >&2'
  printf '%s\n' '  exit 125'
  printf '%s\n' 'fi'
  printf '%s\n' 'if [[ ! -r "$target" || ! -r "$registry" ]]; then'
  printf '%s\n' '  printf '\''[codex-profile] INSTALL_ERROR stable profile CLI is missing\n'\'' >&2'
  printf '%s\n' '  exit 125'
  printf '%s\n' 'fi'
  printf '%s\n' 'exec "$NODE_BIN" "$target" --home "$global_home" --profiles "$global_profiles" --ledger-root "$global_ledger" --registry "$registry" "$@"'
} > "$profile_tmp" \
  || { rm -f "$profile_tmp" 2>/dev/null || true; die "cannot stage global profile shim"; }
chmod 555 "$profile_tmp" \
  || { rm -f "$profile_tmp" 2>/dev/null || true; die "cannot lock global profile shim mode"; }
mv -f "$profile_tmp" "$GLOBAL_PROFILE_SHIM" \
  || { rm -f "$profile_tmp" 2>/dev/null || true; die "cannot publish global profile shim"; }

publish_guard_passthrough() {
  local destination="$1"
  {
    printf '#!/usr/bin/env bash\n'
    printf '%s\n' "$MANAGED_SHIM_SENTINEL"
    printf 'set -u\n'
    printf '%s\n' 'exec codex "$@"'
  } > "$destination" || return 1
  chmod 555 "$destination"
}

if [[ -e "$DISABLE_SENTINEL" || -L "$DISABLE_SENTINEL" ]]; then
  [[ -f "$DISABLE_SENTINEL" && ! -L "$DISABLE_SENTINEL" ]] \
    || die "disable sentinel is not a regular file: $DISABLE_SENTINEL"
  disabled_tmp="$GLOBAL_BIN_DIR/.codex-with-fallback.disabled.$$"
  if [[ -f "$BACKUP" && ! -L "$BACKUP" ]] \
    && ! shim_file_is_managed "$BACKUP"; then
    cp -p "$BACKUP" "$disabled_tmp" \
      || { rm -f "$disabled_tmp" 2>/dev/null || true; die "cannot stage disabled wrapper"; }
    disabled_source="$BACKUP"
  elif [[ -e "$BACKUP" || -L "$BACKUP" ]] \
    && [[ ! -f "$BACKUP" || -L "$BACKUP" ]]; then
    die "guard backup exists but is not a regular file: $BACKUP"
  else
    publish_guard_passthrough "$disabled_tmp" \
      || { rm -f "$disabled_tmp" 2>/dev/null || true; die "cannot stage disabled passthrough"; }
    disabled_source="direct codex passthrough"
  fi
  mv -f "$disabled_tmp" "$GLOBAL_SHIM" \
    || { rm -f "$disabled_tmp" 2>/dev/null || true; die "cannot publish disabled wrapper"; }
  printf '[install-codex-guard] disabled guard; profile converged; published %s\n' "$disabled_source"
else
  shim_tmp="$GLOBAL_BIN_DIR/.codex-with-fallback.tmp.$$"
  {
    printf '#!/usr/bin/env bash\n'
    printf '%s\n' "$MANAGED_SHIM_SENTINEL"
    printf 'set -u\n'
    printf 'target=%q\n' "$CURRENT_LINK/codex-with-fallback.sh"
    printf '%s\n' 'if [[ ! -x "$target" ]]; then'
    printf '%s\n' "  printf '[codex-guard] INSTALL_ERROR stable wrapper is missing\\n' >&2"
    printf '%s\n' '  exit 125'
    printf '%s\n' 'fi'
    printf '%s\n' 'exec "$target" "$@"'
  } > "$shim_tmp" \
    || { rm -f "$shim_tmp" 2>/dev/null || true; die "cannot stage global shim"; }
  chmod 555 "$shim_tmp" \
    || { rm -f "$shim_tmp" 2>/dev/null || true; die "cannot lock global shim mode"; }
  mv -f "$shim_tmp" "$GLOBAL_SHIM" \
    || { rm -f "$shim_tmp" 2>/dev/null || true; die "cannot publish global shim"; }
fi

release_shape() {
  local candidate="$1" entry_count
  entry_count="$(find "$candidate" -mindepth 1 -maxdepth 1 ! -name '.current-*' | wc -l | tr -d ' ')"
  if [[ "$entry_count" == "2" \
    && -f "$candidate/codex-with-fallback.sh" && ! -L "$candidate/codex-with-fallback.sh" \
    && -f "$candidate/codex-guard.sh" && ! -L "$candidate/codex-guard.sh" ]]; then
    printf 'legacy\n'
    return 0
  fi
  if [[ "$entry_count" == "6" ]]; then
    local name
    for name in codex-with-fallback.sh codex-guard.sh flywheel-codex-profile.mjs \
      codex-account-core.mjs codex-account-core.d.mts codex-account-registry.json; do
      [[ -f "$candidate/$name" && ! -L "$candidate/$name" ]] || return 1
    done
    printf 'full\n'
    return 0
  fi
  return 1
}

# Keep current plus two newest prior release directories. Unknown shapes are
# never deleted; both the legacy 2-file and current 6-file layouts are safe.
[[ -d "$CURRENT_LINK" ]] || die "current release is unreadable"
current_release="$release_dir"
newest_prior=""
second_prior=""
for candidate in "$RELEASES_DIR"/*; do
  [[ -d "$candidate" && ! -L "$candidate" ]] || continue
  candidate_name="${candidate##*/}"
  [[ "${#candidate_name}" -eq 64 ]] || continue
  case "$candidate_name" in *[!0-9a-f]*) continue ;; esac
  [[ "$candidate" != "$current_release" ]] || continue
  release_shape "$candidate" >/dev/null || continue
  if [[ -z "$newest_prior" || "$candidate" -nt "$newest_prior" ]]; then
    second_prior="$newest_prior"
    newest_prior="$candidate"
  elif [[ -z "$second_prior" || "$candidate" -nt "$second_prior" ]]; then
    second_prior="$candidate"
  fi
done
for old_release in "$RELEASES_DIR"/*; do
  [[ -d "$old_release" && ! -L "$old_release" ]] || continue
  old_name="${old_release##*/}"
  [[ "${#old_name}" -eq 64 ]] || continue
  case "$old_name" in *[!0-9a-f]*) continue ;; esac
  [[ "$old_release" != "$current_release" \
    && "$old_release" != "$newest_prior" \
    && "$old_release" != "$second_prior" ]] || continue
  shape="$(release_shape "$old_release" 2>/dev/null)" || continue
  if [[ "$shape" == "legacy" ]]; then
    rm -f "$old_release/codex-with-fallback.sh" "$old_release/codex-guard.sh" \
      2>/dev/null || continue
  else
    rm -f "$old_release/codex-with-fallback.sh" "$old_release/codex-guard.sh" \
      "$old_release/flywheel-codex-profile.mjs" \
      "$old_release/codex-account-core.mjs" \
      "$old_release/codex-account-core.d.mts" \
      "$old_release/codex-account-registry.json" 2>/dev/null || continue
  fi
  for current_residue in "$old_release"/.current-*; do
    [[ -L "$current_residue" ]] || continue
    rm -f "$current_residue" 2>/dev/null || true
  done
  rmdir "$old_release" 2>/dev/null || true
done

printf '[install-codex-guard] converged release %s\n' "$content_hash"
